### ISSUE TITLE
sqlalchemy module not found

### ISSUE THREAD

**Issue by shashanksheela** [aws/chalice#1024]
versions:-
virtualenv--16 .0.0
python--3.6.7
chalice--1.6.1
pip-18.0
sqlalchemy--1.2.15

I have chalice project with sqlalchemy dependency and added in the requirements.txt.
chalice local is working fine but when I deploy it to the aws using 'chalice deploy' command
package got created and module got deployed to the aws lambda sucessfully.
If I hit the API then the error is **sqlalchemy not found**

In the package(.chalice/deployments/lambdapackage.zip),I noticed that there is no folder named sqlalchemy instead there is folder named **SQLAlchemy-1.2.15.data**  inside which there is sqlalchemy folder.

Can you please let me know asap what could be wrong with the packaging and why the wrong sqlalchemy got created? Its urgent

Thankyou in advance!!

**Comment by stealthycoin** [comment]
Hrmm I can't repro this with those versions:
```
(env3.6.7) ➜  sqlalchemy chalice --version
chalice 1.6.1, python 3.6.7, darwin 16.7.0

(env3.6.7) ➜  sqlalchemy cat app.py
import sqlalchemy

from chalice import Chalice

app = Chalice(app_name='sqlalchemy')


@app.route('/')
def index():
    return {'version': sqlalchemy.__version__}

(env3.6.7) ➜  sqlalchemy cat requirements.txt
sqlalchemy==1.2.15

(env3.6.7) ➜  sqlalchemy chalice deploy
Creating deployment package.
Updating policy for IAM role: sqlalchemy-dev
Creating lambda function: sqlalchemy-dev
Creating Rest API
Resources deployed:
  - Lambda ARN: arn:aws:lambda:us-west-2:...:function:sqlalchemy-dev
  - Rest API URL: https://....execute-api.us-west-2.amazonaws.com/api/

(env3.6.7) ➜  sqlalchemy curl https://....execute-api.us-west-2.amazonaws.com/api/
{"version": "1.2.15"}
```
When I list the contents its all there.
```
(env3.6.7) ➜  sqlalchemy unzip -l .chalice/deployments/3bfd47b3684ae188ccc60e89f84810b9-python3.6.zip
Archive:  .chalice/deployments/3bfd47b3684ae188ccc60e89f84810b9-python3.6.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
     2249  12-28-2018 13:17   sqlalchemy/__init__.py
    51646  12-28-2018 13:17   sqlalchemy/events.py
    14432  12-28-2018 13:17   sqlalchemy/exc.py
     3093  12-28-2018 13:17   sqlalchemy/inspection.py
    10967  12-28-2018 13:17   sqlalchemy/interfaces.py
     6712  12-28-2018 13:17   sqlalchemy/log.py
    52832  12-28-2018 13:17   sqlalchemy/pool.py
     5104  12-28-2018 13:17   sqlalchemy/processors.py
     1289  12-28-2018 13:17   sqlalchemy/schema.py
.
.
.
```

If you install from the master branch of this repo to get the development version we added debug logs to the packager, running `chalice --debug package out` gives me the following:
```
Creating deployment package.
chalice.deploy.packager [DEBUG] Creating deployment package.
chalice.deploy.packager [DEBUG] calling pip download -r /private/tmp/sqlalchemy/requirements.txt --dest /var/folders/lh/2946pn0x1rg5_bfykvsynh1w0000gn/T/tmp2jcu15xt
chalice.deploy.packager [DEBUG] Full dependency closure: {sqlalchemy==1.2.15(sdist)}
chalice.deploy.packager [DEBUG] initial compatible: set()
chalice.deploy.packager [DEBUG] initial incompatible: {sqlalchemy==1.2.15(sdist)}
chalice.deploy.packager [DEBUG] Downloading missing wheels: {sqlalchemy==1.2.15(sdist)}
chalice.deploy.packager [DEBUG] calling pip download --only-binary=:all: --no-deps --platform manylinux1_x86_64 --implementation cp --abi cp36m --dest /var/folders/lh/2946pn0x1rg5_bfykvsynh1w0000gn/T/tmp2jcu15xt sqlalchemy==1.2.15
chalice.deploy.packager [DEBUG] compatible wheels after second download pass: set()
chalice.deploy.packager [DEBUG] Build missing wheels from sdists (C compiling True): {sqlalchemy==1.2.15(sdist)}
chalice.deploy.packager [DEBUG] calling pip wheel --no-deps --wheel-dir /var/folders/lh/2946pn0x1rg5_bfykvsynh1w0000gn/T/tmp2jcu15xt /var/folders/lh/2946pn0x1rg5_bfykvsynh1w0000gn/T/tmp2jcu15xt/SQLAlchemy-1.2.15.tar.gz
chalice.deploy.packager [DEBUG] compatible after building wheels (no C compiling): set()
chalice.deploy.packager [DEBUG] Build missing wheels from sdists (C compiling False): {sqlalchemy==1.2.15(sdist)}
chalice.deploy.packager [DEBUG] calling pip wheel --no-deps --wheel-dir /var/folders/lh/2946pn0x1rg5_bfykvsynh1w0000gn/T/tmp2jcu15xt /var/folders/lh/2946pn0x1rg5_bfykvsynh1w0000gn/T/tmp2jcu15xt/SQLAlchemy-1.2.15.tar.gz
chalice.deploy.packager [DEBUG] compatible after building wheels (C compiling): set()
chalice.deploy.packager [DEBUG] Final compatible: {sqlalchemy==1.2.15(wheel)}
chalice.deploy.packager [DEBUG] Final incompatible: set()
chalice.deploy.packager [DEBUG] Final missing wheels: set()
```


So basically whats happening here is we get no valid sqlalchemy wheels and we need to compile them ourselves with C extensions disabled in order to get something that will work on lambda. This seems to have worked on my system (os x). What platform are you doing this on? Can you give the output of `chalice --version`. And better yet install chalice from the master branch here and run `chalice --debug package out` and give the output of the packager debugs logs.

**Comment by shashanksheela** [comment]
```
2018-12-29 09:17:43,467 INFO sqlalchemy.engine.base.Engine select version()
2018-12-29 09:17:43,467 INFO sqlalchemy.engine.base.Engine {}
2018-12-29 09:17:43,468 INFO sqlalchemy.engine.base.Engine select current_schema()
2018-12-29 09:17:43,468 INFO sqlalchemy.engine.base.Engine {}
2018-12-29 09:17:43,469 INFO sqlalchemy.engine.base.Engine SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
2018-12-29 09:17:43,469 INFO sqlalchemy.engine.base.Engine {}
2018-12-29 09:17:43,469 INFO sqlalchemy.engine.base.Engine SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
2018-12-29 09:17:43,469 INFO sqlalchemy.engine.base.Engine {}
2018-12-29 09:17:43,470 INFO sqlalchemy.engine.base.Engine show standard_conforming_strings
2018-12-29 09:17:43,470 INFO sqlalchemy.engine.base.Engine {}
2018-12-29 09:17:43,471 INFO sqlalchemy.engine.base.Engine select relname from pg_class c join pg_namespace n on n.oid=c.relnamespace where pg_catalog.pg_table_is_visible(c.oid) and relname=%(name)s
2018-12-29 09:17:43,471 INFO sqlalchemy.engine.base.Engine {'name': 'student'}
2018-12-29 09:17:43,471 INFO sqlalchemy.engine.base.Engine select relname from pg_class c join pg_namespace n on n.oid=c.relnamespace where pg_catalog.pg_table_is_visible(c.oid) and relname=%(name)s
Creating deployment package.
Traceback (most recent call last):
  File "/home/shashank/.virtualenvs/admitally/lib/python3.6/site-packages/chalice/cli/__init__.py", line 447, in main
    return cli(obj={})
  File "/home/shashank/.virtualenvs/admitally/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/shashank/.virtualenvs/admitally/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/shashank/.virtualenvs/admitally/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/shashank/.virtualenvs/admitally/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/shashank/.virtualenvs/admitally/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/shashank/.virtualenvs/admitally/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/shashank/.virtualenvs/admitally/lib/python3.6/site-packages/chalice/cli/__init__.py", line 376, in package
    packager.package_app(config, out, stage)
  File "/home/shashank/.virtualenvs/admitally/lib/python3.6/site-packages/chalice/package.py", line 365, in package_app
    config, chalice_stage_name)
  File "/home/shashank/.virtualenvs/admitally/lib/python3.6/site-packages/chalice/package.py", line 60, in construct_resources
    self._build_stage.execute(config, resources)
  File "/home/shashank/.virtualenvs/admitally/lib/python3.6/site-packages/chalice/deploy/deployer.py", line 823, in execute
    step.handle(config, resource)
  File "/home/shashank/.virtualenvs/admitally/lib/python3.6/site-packages/chalice/deploy/deployer.py", line 721, in handle
    handler(config, resource)
  File "/home/shashank/.virtualenvs/admitally/lib/python3.6/site-packages/chalice/deploy/deployer.py", line 748, in handle_deploymentpackage
    config.project_dir, config.lambda_python_version
  File "/home/shashank/.virtualenvs/admitally/lib/python3.6/site-packages/chalice/deploy/packager.py", line 84, in create_deployment_package
    requirements_filepath, site_packages_dir)
  File "/home/shashank/.virtualenvs/admitally/lib/python3.6/site-packages/chalice/deploy/packager.py", line 478, in build_site_packages
    tempdir, requirements_filepath)
  File "/home/shashank/.virtualenvs/admitally/lib/python3.6/site-packages/chalice/deploy/packager.py", line 357, in _download_dependencies
    requirements_filename, directory)
  File "/home/shashank/.virtualenvs/admitally/lib/python3.6/site-packages/chalice/deploy/packager.py", line 319, in _download_all_dependencies
    self._pip.download_all_dependencies(requirements_filename, directory)
  File "/home/shashank/.virtualenvs/admitally/lib/python3.6/site-packages/chalice/deploy/packager.py", line 715, in download_all_dependencies
    raise NoSuchPackageError(str(package_name))
chalice.deploy.packager.NoSuchPackageError: Could not satisfy the requirement: sqlalchemy

```

**Comment by stealthycoin** [comment]
Is this with the current master branch installed? That error looks like it comes at the end of the packager but there are no packager logs. I can also try to repro this on linux now that I know your platform.

**Comment by stealthycoin** [comment]
Ah I see that python version was broken. Glad you figured it out and got it working.
