### ISSUE TITLE
Fail to import typing at python 3.7 runtime

### ISSUE THREAD

**Issue by sean-ahn** [aws/chalice#1050]
### Problem
`chalice` fails when trying to import a `typing` module at python 3.7 runtime.

### CloudWatch Logs
```
[ERROR] AttributeError: type object 'Callable' has no attribute '_abc_registry'
Traceback (most recent call last):
  File "/var/lang/lib/python3.7/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/var/lang/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/var/task/app.py", line 4, in <module>
    from typing import Optional
  File "/var/task/typing.py", line 1347, in <module>
    class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):
  File "/var/task/typing.py", line 1003, in __new__
    self._abc_registry = extra._abc_registry
```

### Reason
This issue is known to occur when importing a backport instead of the stdlib typing module in python 3.7. (Reference: [python typing module](https://github.com/python/typing/issues/573))
> `typing` is in the standard library since 3.5. 

### Suggestion
Ignore `typing` at `install_requires` when python_version is 3.7 (or both of 3.7 and 3.6).

(References: [alexa-skills-kit-sdk-for-python](https://github.com/alexa/alexa-skills-kit-sdk-for-python/issues/49), [zulip-terminal](https://github.com/zulip/zulip-terminal/pull/196))

**Comment by stealthycoin** [comment]
Closing since the PR was merged.
