### ISSUE TITLE
Feature Request: Chalice with LocalStack

### ISSUE THREAD

**Issue by orhaneee** [aws/chalice#1089]
As you might know [localstack](https://github.com/localstack/localstack) is pretty good for debugging cloud apps in local.

We are using SQS so, in order to test it we need to deploy it every time. I think it would be perfect to use chalice with localstack.

**Comment by stealthycoin** [comment]
Just for clarity, the feature request here would be to use `chalice deploy` with maybe an extra flag that let you control the endpoints it hits so you could configure it to use all those local service endpoints?

**Comment by kapilt** [comment]
i think the request is a bit different then deploy options, it sounds like application defined sessions using local endpoints, which is something the application can already do independent of chalice. ie. chalice doesn't create sessions the application using chalice does. your application use an environment variable (AWS_DEV_LOCAL) and then when creating boto3 sessions/clients pass in endpoint_url per the README on localstack, https://github.com/localstack/localstack#client-libraries

**Comment by yannbr** [comment]
@xerdink @stealthycoin Did you found another way around this topic?

This would be a great feature to have, as @stealthycoin said, a way to add a flag to the "deploy" function (or using the config.json file), and to be able to release on the API Gateway of the localstack running instance

**Comment by tasercake** [comment]
I too would be interested in deploying to LocalStack from Chalice.

There's now a wrapper from the folks at LocalStack - [`chalice-local`](https://github.com/localstack/chalice-local), which appears to patch the default endpoint used by Chalice's botocore Session and pointing it at LocalStack.

It would still be great to have native support for custom endpoints though.

**Comment by brianmingus2** [comment]
chalice-local does not work.

```
$ chalice-local deploy
Creating deployment package.
Creating IAM role: Maggie-dev
Traceback (most recent call last):
  File "/home/mingus/anaconda3/lib/python3.8/site-packages/chalice-1.22.1-py3.8.egg/chalice/deploy/deployer.py", line 376, in deploy
    return self._deploy(config, chalice_stage_name)
  File "/home/mingus/anaconda3/lib/python3.8/site-packages/chalice-1.22.1-py3.8.egg/chalice/deploy/deployer.py", line 392, in _deploy
    self._executor.execute(plan)
  File "/home/mingus/anaconda3/lib/python3.8/site-packages/chalice-1.22.1-py3.8.egg/chalice/deploy/executor.py", line 42, in execute
    getattr(self, '_do_%s' % instruction.__class__.__name__.lower(),
  File "/home/mingus/anaconda3/lib/python3.8/site-packages/chalice-1.22.1-py3.8.egg/chalice/deploy/executor.py", line 55, in _do_apicall
    result = method(**final_kwargs)
  File "/home/mingus/anaconda3/lib/python3.8/site-packages/chalice-1.22.1-py3.8.egg/chalice/awsclient.py", line 1022, in create_role
    raise e
  File "/home/mingus/anaconda3/lib/python3.8/site-packages/chalice-1.22.1-py3.8.egg/chalice/awsclient.py", line 1018, in create_role
    self.put_role_policy(role_name=name, policy_name=name,
  File "/home/mingus/anaconda3/lib/python3.8/site-packages/chalice-1.22.1-py3.8.egg/chalice/awsclient.py", line 1004, in put_role_policy
    self._client('iam').put_role_policy(
  File "/home/mingus/anaconda3/lib/python3.8/site-packages/botocore-1.20.7-py3.8.egg/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/mingus/anaconda3/lib/python3.8/site-packages/botocore-1.20.7-py3.8.egg/botocore/client.py", line 676, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.MalformedPolicyDocumentException: An error occurred (MalformedPolicyDocument) when calling the PutRolePolicy operation: Partition "*" is not valid for resource "arn:*:logs:*:*:*".

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mingus/anaconda3/lib/python3.8/site-packages/chalice-1.22.1-py3.8.egg/chalice/cli/__init__.py", line 636, in main
    return cli(obj={})
  File "/home/mingus/anaconda3/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/mingus/anaconda3/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/mingus/anaconda3/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/mingus/anaconda3/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/mingus/anaconda3/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/mingus/anaconda3/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/mingus/anaconda3/lib/python3.8/site-packages/chalice-1.22.1-py3.8.egg/chalice/cli/__init__.py", line 189, in deploy
    deployed_values = d.deploy(config, chalice_stage_name=stage)
  File "/home/mingus/anaconda3/lib/python3.8/site-packages/chalice-1.22.1-py3.8.egg/chalice/deploy/deployer.py", line 378, in deploy
    raise ChaliceDeploymentError(e)
chalice.deploy.deployer.ChaliceDeploymentError: ERROR - While deploying your chalice application, received the following error:

 An error occurred (MalformedPolicyDocument) when calling the PutRolePolicy
 operation: Partition "*" is not valid for resource "arn:*:logs:*:*:*".
```

**Comment by tasercake** [comment]
@brianmingus2 I haven't been able to get it working either unfortunately, but I was able to get past that particular error.

The issue appears to be that localstack doesn't support ARN partitions other than `aws` (i.e. only ARNs of the form `arn:aws:*` are supported) whereas Chalice seems to be trying to support other partitions as well (`aws-cn` and `aws-us-gov`).

In [`chalice/constants.py`](https://github.com/aws/chalice/blob/f4eb00238970d919d28c1507386e16f87ed56292/chalice/constants.py#L82), `CLOUDWATCH_LOGS` has `Resource` set to `"arn:*:logs:*:*:*"`. Changing this to `"arn:aws:*:*:*"` bypasses the issue, but I still face other errors trying to deploy on localstack.
