### ISSUE TITLE
Unable to deploy chalice app due to layers issue

### ISSUE THREAD

**Issue by dperconti** [aws/chalice#1142]
## The Error

```
$ chalice new-project helloworld && cd helloworld
$ chalice deploy
Creating deployment package.
Updating policy for IAM role: helloworld-dev
Updating lambda function: helloworld-dev
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/chalice/cli/__init__.py", line 463, in main
    return cli(obj={})
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/chalice/cli/__init__.py", line 199, in deploy
    deployed_values = d.deploy(config, chalice_stage_name=stage)
  File "/usr/local/lib/python3.7/site-packages/chalice/deploy/deployer.py", line 330, in deploy
    return self._deploy(config, chalice_stage_name)
  File "/usr/local/lib/python3.7/site-packages/chalice/deploy/deployer.py", line 343, in _deploy
    self._executor.execute(plan)
  File "/usr/local/lib/python3.7/site-packages/chalice/deploy/executor.py", line 31, in execute
    self._default_handler)(instruction)
  File "/usr/local/lib/python3.7/site-packages/chalice/deploy/executor.py", line 43, in _do_apicall
    result = method(**final_kwargs)
  File "/usr/local/lib/python3.7/site-packages/chalice/awsclient.py", line 283, in update_function
    layers=layers
  File "/usr/local/lib/python3.7/site-packages/chalice/awsclient.py", line 352, in _update_function_config
    max_attempts=self.LAMBDA_CREATE_ATTEMPTS
  File "/usr/local/lib/python3.7/site-packages/chalice/awsclient.py", line 1001, in _call_client_method_with_retries
    response = method(**kwargs)
  File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 314, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 586, in _make_api_call
    api_params, operation_model, context=request_context)
  File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 621, in _convert_to_request_dict
    api_params, operation_model)
  File "/usr/local/lib/python3.7/site-packages/botocore/validate.py", line 291, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
botocore.exceptions.ParamValidationError: Parameter validation failed:
Unknown parameter in input: "Layers", must be one of: FunctionName, Role, Handler, Description, Timeout, MemorySize, VpcConfig, Environment, Runtime, DeadLetterConfig, KMSKeyArn, TracingConfig, RevisionId
```

## Env Info
```
$ pip freeze
atomicwrites==1.3.0
attrs==17.4.0
boto3==1.9.160
botocore==1.12.160
chalice==1.8.0
click==6.7
docutils==0.14
enum-compat==0.0.2
importlib-metadata==0.17
jmespath==0.9.4
more-itertools==7.0.0
packaging==19.0
pluggy==0.9.0
py==1.8.0
pyparsing==2.4.0
pytest==4.4.1
python-dateutil==2.8.0
PyYAML==5.1
s3transfer==0.2.0
six==1.12.0
typing==3.6.4
urllib3==1.24.3
wcwidth==0.1.7
zipp==0.5.1
```

I'm assuming this is a dependency issue, but let me know what versions I should be using &/or if any more information is required.

**Comment by dperconti** [comment]
Turns out we were running into our API edge endpoint limit. Once that was resolved we were able to deploy just fine.
