### ISSUE TITLE
Can't find boto3, even though it's installed

### ISSUE THREAD

**Issue by gusgordon** [aws/chalice#1153]
When I add a line `import boto3` in `app.py`, I get the following exception:
```
chalice deploy
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/chalice/cli/__init__.py", line 463, in main
    return cli(obj={})
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/chalice/cli/__init__.py", line 199, in deploy
    deployed_values = d.deploy(config, chalice_stage_name=stage)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/chalice/deploy/deployer.py", line 330, in deploy
    return self._deploy(config, chalice_stage_name)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/chalice/deploy/deployer.py", line 336, in _deploy
    self._validate_config(config)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/chalice/deploy/deployer.py", line 359, in _validate_config
    validate_configuration(config)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/chalice/deploy/validate.py", line 38, in validate_configuration
    routes = config.chalice_app.routes
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/chalice/config.py", line 140, in chalice_app
    app = v()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/chalice/cli/factory.py", line 255, in load_chalice_app
    app = importlib.import_module('app')
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/gusgordon/repos/briskvoyage/teller/app.py", line 3, in <module>
    import boto3
ModuleNotFoundError: No module named 'boto3'
```

boto3 appears to be installed in my virtualenv
```
pip freeze
boto3==1.9.174
botocore==1.12.174
docutils==0.14
jmespath==0.9.4
python-dateutil==2.8.0
s3transfer==0.2.1
six==1.12.0
urllib3==1.25.3
```

and it's importable if I try manually:
```
python 
Python 3.7.3 (default, Mar 27 2019, 16:54:48) 
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import boto3
>>>
```

It's also in my `requirements.txt`:
```
boto3

```

So what gives? Any idea why Chalice complains here?

**Comment by kapilt** [comment]
you referenced a virtualenv, but your original traceback shows a system install, perhaps your seeing some oddities from mixing the two. i'd suggest installing chalice in the virtualenv. the lambda environment includes an old boto library as well.

**Comment by gusgordon** [comment]
Thanks! That was it
