### ISSUE TITLE
"chalice deploy" call ends up with Unknown parameter in input: "Layers"

### ISSUE THREAD

**Issue by Beeezus** [aws/chalice#1173]
I create the most bascic app.pythat loocks like this

`from chalice import Chalice

app = Chalice(app_name='testApp')

@app.route('/')
def index():
    return {'hello': 'world'}`

 with empty requirements.txt and config.json:

`{
  "version": "2.0",
  "app_name": "testApp",
  "stages": {
    "dev": {
      "api_gateway_stage": "api"
    }
  }
}`

The error is this:
chalice deploy
Creating deployment package.
Updating policy for IAM role: testApp-dev
Updating lambda function: testApp-dev
Traceback (most recent call last):
  File "c:\users\vic\appdata\local\programs\python\python37-32\lib\site-packages\chalice\cli\__init__.py", line 466, in main
    return cli(obj={})
  File "c:\users\vic\appdata\local\programs\python\python37-32\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\vic\appdata\local\programs\python\python37-32\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "c:\users\vic\appdata\local\programs\python\python37-32\lib\site-packages\click\core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\vic\appdata\local\programs\python\python37-32\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\vic\appdata\local\programs\python\python37-32\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "c:\users\vic\appdata\local\programs\python\python37-32\lib\site-packages\click\decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "c:\users\vic\appdata\local\programs\python\python37-32\lib\site-packages\chalice\cli\__init__.py", line 202, in deploy
    deployed_values = d.deploy(config, chalice_stage_name=stage)
  File "c:\users\vic\appdata\local\programs\python\python37-32\lib\site-packages\chalice\deploy\deployer.py", line 342, in deploy
    return self._deploy(config, chalice_stage_name)
  File "c:\users\vic\appdata\local\programs\python\python37-32\lib\site-packages\chalice\deploy\deployer.py", line 355, in _deploy
    self._executor.execute(plan)
  File "c:\users\vic\appdata\local\programs\python\python37-32\lib\site-packages\chalice\deploy\executor.py", line 31, in execute
    self._default_handler)(instruction)
  File "c:\users\vic\appdata\local\programs\python\python37-32\lib\site-packages\chalice\deploy\executor.py", line 43, in _do_apicall
    result = method(**final_kwargs)
  File "c:\users\vic\appdata\local\programs\python\python37-32\lib\site-packages\chalice\awsclient.py", line 283, in update_function
    layers=layers
  File "c:\users\vic\appdata\local\programs\python\python37-32\lib\site-packages\chalice\awsclient.py", line 352, in _update_function_config
    max_attempts=self.LAMBDA_CREATE_ATTEMPTS
  File "c:\users\vic\appdata\local\programs\python\python37-32\lib\site-packages\chalice\awsclient.py", line 1009, in _call_client_method_with_retries
    response = method(**kwargs)
  File "c:\users\vic\appdata\local\programs\python\python37-32\lib\site-packages\botocore\client.py", line 314, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "c:\users\vic\appdata\local\programs\python\python37-32\lib\site-packages\botocore\client.py", line 586, in _make_api_call
    api_params, operation_model, context=request_context)
  File "c:\users\vic\appdata\local\programs\python\python37-32\lib\site-packages\botocore\client.py", line 621, in _convert_to_request_dict
    api_params, operation_model)
  File "c:\users\vic\appdata\local\programs\python\python37-32\lib\site-packages\botocore\validate.py", line 291, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
botocore.exceptions.ParamValidationError: Parameter validation failed:
Unknown parameter in input: "Layers", must be one of: FunctionName, Role, Handler, Description, Timeout, MemorySize, VpcConfig, Environment, Runtime, DeadLetterConfig, KMSKeyArn, TracingConfig, RevisionId

**Comment by Beeezus** [comment]
found out that the issue was with my local configuration. Resolved by running the chalice in virtualenv
