### ISSUE TITLE
Route cannot end with a trailing slash

### ISSUE THREAD

**Issue by katouyuta** [aws/chalice#1230]
I want to specify root for a sub-app

http://localhost/subapp <-  call subapp in index Should it be possible?
http://localhost/subapp/subtest <- call subapp_subtest

````
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/Users/me/.pyenv/versions/3.7.0/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/Users/me/pyenv/3.7.0/lib/python3.7/site-packages/chalice/local.py", line 659, in run
    self._server = self._server_factory()
  File "/Users/me/pyenv/3.7.0/lib/python3.7/site-packages/chalice/cli/__init__.py", line 160, in create_local_server
    validate_routes(routes)
  File "/Users/me/pyenv/3.7.0/lib/python3.7/site-packages/chalice/deploy/validate.py", line 107, in validate_routes
    % route_name)
ValueError: Route cannot end with a trailing slash: /subapp/
````

app.py

```
from chalicelib.SubApp import subApp
app = Chalice(app_name='test-api')
app.experimental_feature_flags.update([
        'BLUEPRINTS'
])
app.register_blueprint(
    subApp, url_prefix='/subapp')
```

SubApp.py
```
subApp = Blueprint(__name__)

@subApp.route('/')
def subapp_index():
    print("this config is not work")
    return {}

@subApp.route('/subtest')
def subapp_subtest():
    print("it work")
    return {}
```

**Comment by stealthycoin** [comment]
merged in https://github.com/aws/chalice/commit/562f2803ea99b096f3cd752e184f6035ce3e0f20
