### ISSUE TITLE
Multiple SQS queues

### ISSUE THREAD

**Issue by DannyAziz** [aws/chalice#1283]
So I built this simple test chalice project which uses boto to send a message to another task queue
```
@app.on_sqs_message(queue='test')
def handler_test_queue(event):
    for record in event:
        queue = sqs.get_queue_by_name(QueueName='test_other')
        queue.send_message(
            MessageBody="Message sent from test queue: {message}".format(message=record.body)
        )


@app.on_sqs_message(queue='test_other')
def handler_test_other_queue(event):
    for record in event:
        print("Message body: %s" % record.body)
```

When trying to deploy I get this error message:
```
Creating deployment package.
Updating policy for IAM role: jetorget_tasks-dev
Creating lambda function: jetorget_tasks-dev-handler_test_queue
Subscribing jetorget_tasks-dev-handler_test_queue to SQS queue test
Creating lambda function: jetorget_tasks-dev-handler_test_other_queue
Subscribing jetorget_tasks-dev-handler_test_other_queue to SQS queue test_other
Deleting function: arn:aws:lambda:eu-west-1:203882818477:function:jetorget_tasks-dev-handler
Traceback (most recent call last):
  File "/Users/danny/.virtualenvs/jetorget_serverless/lib/python3.7/site-packages/chalice/awsclient.py", line 248, in delete_function
    lambda_client.delete_function(FunctionName=function_name)
  File "/Users/danny/.virtualenvs/jetorget_serverless/lib/python3.7/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/danny/.virtualenvs/jetorget_serverless/lib/python3.7/site-packages/botocore/client.py", line 661, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.ResourceNotFoundException: An error occurred (ResourceNotFoundException) when calling the DeleteFunction operation: 
Function not found: arn:aws:lambda:eu-west-1:203882818477:function:jetorget_tasks-dev-handler

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/danny/.virtualenvs/jetorget_serverless/lib/python3.7/site-packages/chalice/deploy/deployer.py", line 342, in deploy
    return self._deploy(config, chalice_stage_name)
  File "/Users/danny/.virtualenvs/jetorget_serverless/lib/python3.7/site-packages/chalice/deploy/deployer.py", line 355, in _deploy
    self._executor.execute(plan)
  File "/Users/danny/.virtualenvs/jetorget_serverless/lib/python3.7/site-packages/chalice/deploy/executor.py", line 31, in execute
    self._default_handler)(instruction)
  File "/Users/danny/.virtualenvs/jetorget_serverless/lib/python3.7/site-packages/chalice/deploy/executor.py", line 43, in _do_apicall
    result = method(**final_kwargs)
  File "/Users/danny/.virtualenvs/jetorget_serverless/lib/python3.7/site-packages/chalice/awsclient.py", line 250, in delete_function
    raise ResourceDoesNotExistError(function_name)
chalice.awsclient.ResourceDoesNotExistError: arn:aws:lambda:eu-west-1:203882818477:function:jetorget_tasks-dev-handler

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/danny/.virtualenvs/jetorget_serverless/lib/python3.7/site-packages/chalice/cli/__init__.py", line 466, in main
    return cli(obj={})
  File "/Users/danny/.virtualenvs/jetorget_serverless/lib/python3.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/danny/.virtualenvs/jetorget_serverless/lib/python3.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/danny/.virtualenvs/jetorget_serverless/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/danny/.virtualenvs/jetorget_serverless/lib/python3.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/danny/.virtualenvs/jetorget_serverless/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/danny/.virtualenvs/jetorget_serverless/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/danny/.virtualenvs/jetorget_serverless/lib/python3.7/site-packages/chalice/cli/__init__.py", line 202, in deploy
    deployed_values = d.deploy(config, chalice_stage_name=stage)
  File "/Users/danny/.virtualenvs/jetorget_serverless/lib/python3.7/site-packages/chalice/deploy/deployer.py", line 344, in deploy
    raise ChaliceDeploymentError(e)
chalice.deploy.deployer.ChaliceDeploymentError: ERROR - While deploying your chalice application, received the following error:

 arn:aws:lambda:eu-west-1:203882818477:function:jetorget_tasks-dev-handler
```

However, it seems to work perfectly. 2 separate lamba functions are created and when checking the logs for the function that handles `test_other` the messages are printed to the log

**Comment by stealthycoin** [comment]
Interesting, I took your code and created my own SQS queues and it appears to deploy fine on python 3.7 in the same region:

```
$ chalice deploy
Creating deployment package.
Updating policy for IAM role: double-sqs-dev
Updating lambda function: double-sqs-dev-handler_test_queue
Subscribing double-sqs-dev-handler_test_queue to SQS queue test
Creating lambda function: double-sqs-dev-handler_test_other_queue
Subscribing double-sqs-dev-handler_test_other_queue to SQS queue test_other
Resources deployed:
  - Lambda ARN: arn:aws:lambda:eu-west-1:<id>:function:double-sqs-dev-handler_test_queue
  - Lambda ARN: arn:aws:lambda:eu-west-1:<id>:function:double-sqs-dev-handler_test_other_queue
```

Does this happen consistently? Can you give me the output of `chalice --debug deploy` if it does happen consistently?

**Comment by DannyAziz** [comment]
I will create a new chalice project and try again - will report back soon

**Comment by stealthycoin** [comment]
Reopen if you continue to have issues.
