### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte

### ISSUE THREAD

**Issue by industrydatauser-at-159025770342** [aws/chalice#1285]
Hi,
I've got an issue doing a chalice package or deploy when running in linux in docker. I can't track down the issue and the error message doesn't help much (well help me anyway).
It packages and deploys fine from my Windows machine, but when I push into gitlab and run my pipeline it errors out.

$ chalice deploy
Creating deployment package.
/usr/local/lib/python3.6/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/chalice/cli/__init__.py", line 447, in main
    return cli(obj={})
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/chalice/cli/__init__.py", line 183, in deploy
    deployed_values = d.deploy(config, chalice_stage_name=stage)
  File "/usr/local/lib/python3.6/site-packages/chalice/deploy/deployer.py", line 330, in deploy
    return self._deploy(config, chalice_stage_name)
  File "/usr/local/lib/python3.6/site-packages/chalice/deploy/deployer.py", line 340, in _deploy
    self._build_stage.execute(config, resources)
  File "/usr/local/lib/python3.6/site-packages/chalice/deploy/deployer.py", line 823, in execute
    step.handle(config, resource)
  File "/usr/local/lib/python3.6/site-packages/chalice/deploy/deployer.py", line 721, in handle
    handler(config, resource)
  File "/usr/local/lib/python3.6/site-packages/chalice/deploy/deployer.py", line 748, in handle_deploymentpackage
    config.project_dir, config.lambda_python_version
  File "/usr/local/lib/python3.6/site-packages/chalice/deploy/packager.py", line 84, in create_deployment_package
    requirements_filepath, site_packages_dir)
  File "/usr/local/lib/python3.6/site-packages/chalice/deploy/packager.py", line 475, in build_site_packages
    if self._has_at_least_one_package(requirements_filepath):
  File "/usr/local/lib/python3.6/site-packages/chalice/deploy/packager.py", line 306, in _has_at_least_one_package
    for line in f:
  File "/usr/local/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte

My requirements.txt file includes-
chalice==1.6.1
psycopg2==2.7.6.1

My script is-
pip install -r requirements.txt
chalice deploy

Package also fails with the same error.

If someone could give me a heads up on where I should be looking. Other projects have used Chalice successuly with the same images in Gitlab so I dont think it is the Gitlab set up. I've tried removing psycopg2 and all references to it in the code and that didnt help. I'm not sure where else to check, any help would be much appreciated.

**Comment by stealthycoin** [comment]
Looks like its asking you to change your dependency to  `psycopg2-binary`. Can you try that and see if it works?

**Comment by industrydatauser-at-159025770342** [comment]
Thanks for the reply.
Apologies, i forgot to mention i did try different version of psycopg2 including using the binary and also removing it from the project all together but it still fails. Here is the run I just did using the psycopg2-binary-


$ chalice deploy
Creating deployment package.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/chalice/cli/__init__.py", line 447, in main
    return cli(obj={})
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/chalice/cli/__init__.py", line 183, in deploy
    deployed_values = d.deploy(config, chalice_stage_name=stage)
  File "/usr/local/lib/python3.6/site-packages/chalice/deploy/deployer.py", line 330, in deploy
    return self._deploy(config, chalice_stage_name)
  File "/usr/local/lib/python3.6/site-packages/chalice/deploy/deployer.py", line 340, in _deploy
    self._build_stage.execute(config, resources)
  File "/usr/local/lib/python3.6/site-packages/chalice/deploy/deployer.py", line 823, in execute
    step.handle(config, resource)
  File "/usr/local/lib/python3.6/site-packages/chalice/deploy/deployer.py", line 721, in handle
    handler(config, resource)
  File "/usr/local/lib/python3.6/site-packages/chalice/deploy/deployer.py", line 748, in handle_deploymentpackage
    config.project_dir, config.lambda_python_version
  File "/usr/local/lib/python3.6/site-packages/chalice/deploy/packager.py", line 84, in create_deployment_package
    requirements_filepath, site_packages_dir)
  File "/usr/local/lib/python3.6/site-packages/chalice/deploy/packager.py", line 475, in build_site_packages
    if self._has_at_least_one_package(requirements_filepath):
  File "/usr/local/lib/python3.6/site-packages/chalice/deploy/packager.py", line 306, in _has_at_least_one_package
    for line in f:
  File "/usr/local/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte

**Comment by stealthycoin** [comment]
Oh I see. Whats the content of your requirements.txt file? It looks like maybe you have an invalid character in it that we fail on when its loading the content of that file.

**Comment by industrydatauser-at-159025770342** [comment]
You are right. I deleted everything out of the file but still got an error. I deleted the file completelty out of source control and it was ok. Ill generate a new requirements.txt and go from there. Thanks for your help, this issue can close

**Comment by stealthycoin** [comment]
Interesting, 0xff isn't a common one so I don't know where that came from!

**Comment by Dharanidaran** [comment]
Save the requirement.txt file as a UTF-8 file. This solved my problem.
Open it with a text editor that can save it as UTF-8. Notepad++ or sublime can do it. 

![image](https://user-images.githubusercontent.com/17711227/80179412-c6b39000-8600-11ea-846d-035469ef23bf.png)
