### ISSUE TITLE
chalice watcher attempts to read node_modules

### ISSUE THREAD

**Issue by Kartstig** [aws/chalice#1320]
I'm experiencing an issue with the reloader. I have a directory labeled `frontend` which houses the frontend of my app. I think Chalice is trying to read files within this directory
```
Serving on http://127.0.0.1:5000
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/herman/dev/spinflip-marketing/venv/lib/python3.6/site-packages/chalice/cli/filewatch/stat.py", line 49, in poll_for_changes_until_shutdown
    self._seed_mtime_cache(root_dir)
  File "/home/herman/dev/spinflip-marketing/venv/lib/python3.6/site-packages/chalice/cli/filewatch/stat.py", line 59, in _seed_mtime_cache
    self._mtime_cache[path] = self._osutils.mtime(path)
  File "/home/herman/dev/spinflip-marketing/venv/lib/python3.6/site-packages/chalice/utils.py", line 249, in mtime
    return os.stat(path).st_mtime
FileNotFoundError: [Errno 2] No such file or directory: '/home/herman/dev/spinflip-marketing/frontend/node_modules/node-releases/node_modules/.bin/semver'

```

This would be fine, but my guess is that it's encountering a symlink in the mess of node_modules. I tried searching for a way to omit or specify a directory to watch, but couldn't find it.

**Comment by jamesls** [comment]
Confirmed bug: https://github.com/aws/chalice/issues/997.  Let's track the remaining work there.

I'm also somewhat inclined to just have a default list of directories to ignore, `.node_modules`, but I'm leaning towards letting users configure that.
