### ISSUE TITLE
Chalice hello-world fails with Internal Server Error

### ISSUE THREAD

**Issue by liquidcarbon** [aws/chalice#1350]
HTTPie:

```
HTTP/1.1 502 Bad Gateway
Connection: keep-alive
Content-Length: 36
Content-Type: application/json
Date: Wed, 12 Feb 2020 16:36:58 GMT
Via: 1.1 8b557fcfe676507ad235f89c0a02c05b.cloudfront.net (CloudFront)
X-Amz-Cf-Id: xN6ZRkWXOcqliNQYGt2roxRSqt7QEh-Oe2YgJCgyIgiW_-ZLWQowrA==
X-Amz-Cf-Pop: ORD50-C1
X-Cache: Error from cloudfront
x-amz-apigw-id: HytyYG5IiYcFq3g=
x-amzn-ErrorType: InternalServerErrorException
x-amzn-RequestId: 7b6d7241-d670-4e79-82d5-babcaae5deb2

{
    "message": "Internal server error"
}
```

Cloudwatch:
```

16:27:52
[ERROR] PermissionError: [Errno 13] Permission denied: '/var/task/chalice/__init__.py' Traceback (most recent call last):   File "/var/lang/lib/python3.7/imp.py", line 234, in load_module     return load_source(name, filename, file)   File "/var/lang/lib/python3.7/imp.py", line 171, in load_source     module = _load(spec)   File "<frozen importlib._bootstrap>", line 696, in _load   File "<frozen i

16:27:52
START RequestId: 52b1ea28-156c-494d-8038-8d91019794ef Version: $LATEST

16:27:53
[ERROR] PermissionError: [Errno 13] Permission denied: '/var/task/chalice/__init__.py' Traceback (most recent call last):   File "/var/lang/lib/python3.7/imp.py", line 234, in load_module     return load_source(name, filename, file)   File "/var/lang/lib/python3.7/imp.py", line 171, in load_source     module = _load(spec)   File "<frozen importlib._bootstrap>", line 696, in _load   File "<frozen i

16:27:54
END RequestId: 52b1ea28-156c-494d-8038-8d91019794ef

16:27:54
REPORT RequestId: 52b1ea28-156c-494d-8038-8d91019794ef Duration: 1442.21 ms Billed Duration: 1500 ms Memory Size: 128 MB Max Memory Used: 21 MB

16:27:54
Unknown application error occurred

16:27:54
[ERROR] PermissionError: [Errno 13] Permission denied: '/var/task/chalice/__init__.py' Traceback (most recent call last):   File "/var/lang/lib/python3.7/imp.py", line 234, in load_module     return load_source(name, filename, file)   File "/var/lang/lib/python3.7/imp.py", line 171, in load_source     module = _load(spec)   File "<frozen importlib._bootstrap>", line 696, in _load   File "<frozen i

16:29:35
START RequestId: ebb90d28-67e9-4b19-9ce1-bdf8d8d75e2d Version: $LATEST

16:29:36
[ERROR] PermissionError: [Errno 13] Permission denied: '/var/task/chalice/__init__.py' Traceback (most recent call last):   File "/var/lang/lib/python3.7/imp.py", line 234, in load_module     return load_source(name, filename, file)   File "/var/lang/lib/python3.7/imp.py", line 171, in load_source     module = _load(spec)   File "<frozen importlib._bootstrap>", line 696, in _load   File "<frozen i

16:29:36
END RequestId: ebb90d28-67e9-4b19-9ce1-bdf8d8d75e2d

16:29:36
REPORT RequestId: ebb90d28-67e9-4b19-9ce1-bdf8d8d75e2d Duration: 1405.64 ms Billed Duration: 1500 ms Memory Size: 128 MB Max Memory Used: 20 MB

16:29:36
Unknown application error occurred

16:29:36
[ERROR] PermissionError: [Errno 13] Permission denied: '/var/task/chalice/__init__.py' Traceback (most recent call last):   File "/var/lang/lib/python3.7/imp.py", line 234, in load_module
```

Lambda test result:
```
Response:
{
  "errorMessage": "[Errno 13] Permission denied: '/var/task/chalice/__init__.py'",
  "errorType": "PermissionError",
  "stackTrace": [
    "  File \"/var/lang/lib/python3.7/imp.py\", line 234, in load_module\n    return load_source(name, filename, file)\n",
    "  File \"/var/lang/lib/python3.7/imp.py\", line 171, in load_source\n    module = _load(spec)\n",
    "  File \"<frozen importlib._bootstrap>\", line 696, in _load\n",
    "  File \"<frozen importlib._bootstrap>\", line 677, in _load_unlocked\n",
    "  File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n",
    "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
    "  File \"/var/task/app.py\", line 1, in <module>\n    from chalice import Chalice\n",
    "  File \"<frozen importlib._bootstrap>\", line 983, in _find_and_load\n",
    "  File \"<frozen importlib._bootstrap>\", line 967, in _find_and_load_unlocked\n",
    "  File \"<frozen importlib._bootstrap>\", line 677, in _load_unlocked\n",
    "  File \"<frozen importlib._bootstrap_external>\", line 724, in exec_module\n",
    "  File \"<frozen importlib._bootstrap_external>\", line 859, in get_code\n",
    "  File \"<frozen importlib._bootstrap_external>\", line 916, in get_data\n"
  ]
}

Request ID:
"ebb90d28-67e9-4b19-9ce1-bdf8d8d75e2d"

Function Logs:
START RequestId: ebb90d28-67e9-4b19-9ce1-bdf8d8d75e2d Version: $LATEST
[ERROR] PermissionError: [Errno 13] Permission denied: '/var/task/chalice/__init__.py'
Traceback (most recent call last):
  File "/var/lang/lib/python3.7/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/var/lang/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/var/task/app.py", line 1, in <module>
    from chalice import Chalice
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 859, in get_code
  File "<frozen importlib._bootstrap_external>", line 916, in get_data
END RequestId: ebb90d28-67e9-4b19-9ce1-bdf8d8d75e2d
REPORT RequestId: ebb90d28-67e9-4b19-9ce1-bdf8d8d75e2d	Duration: 1405.64 ms	Billed Duration: 1500 ms	Memory Size: 128 MB	Max Memory Used: 20 MB	
Unknown application error occurred
```

**Comment by liquidcarbon** [comment]
This had to do with how I installed chalice.  My /opt/conda permissions are set to 660/770 via `setfacl -R -d -m g::rwx /opt/conda`, therefore the app.py and __init__.py files that are packaged into the ZIP archive for deployment came through as unreadable.  Fixed with `chmod -R o+r /opt/conda/a3/lib/python3.7/site-packages/chalice/`

**Comment by jamesls** [comment]
Glad you were able to get it working!
