### ISSUE TITLE
watchdog is required

### ISSUE THREAD

**Issue by sproctor** [aws/chalice#1355]
a recent change has caused chalice to fail if watchdog is not installed

**Comment by jamesls** [comment]
I'm not seeing that.  Could you share a set of steps I can follow or share more information about what you're seeing?  Here's what I tried:

```
/tmp/repro $ python3 -m venv venv
/tmp/repro $ . venv/bin/activate
(venv) /tmp/repro $ pip install chalice
Collecting chalice
  Using cached https://files.pythonhosted.org/packages/a9/90/5358f8b1e3739c544d2b03ecfd67d9a7681f7dfa519df4c7763475e5e0e3/chalice-1.12.0-py2.py3-none-any.whl
Collecting botocore<2.0.0,>=1.12.86 (from chalice)
  Downloading https://files.pythonhosted.org/packages/40/2b/f290e79241a6b07ab955a65d0395128bb300711ef37589a01696de1c5b5f/botocore-1.15.5-py2.py3-none-any.whl (5.9MB)
    100% |████████████████████████████████| 5.9MB 4.7MB/s
Requirement already satisfied: setuptools in ./venv/lib/python3.7/site-packages (from chalice) (40.8.0)
Collecting six<2.0.0,>=1.10.0 (from chalice)
  Using cached https://files.pythonhosted.org/packages/65/eb/1f97cb97bfc2390a276969c6fae16075da282f5058082d4cb10c6c5c1dba/six-1.14.0-py2.py3-none-any.whl
Collecting click<8.0,>=6.6 (from chalice)
  Using cached https://files.pythonhosted.org/packages/fa/37/45185cb5abbc30d7257104c434fe0b07e5a195a6847506c074527aa599ec/Click-7.0-py2.py3-none-any.whl
Collecting jmespath<1.0.0,>=0.9.3 (from chalice)
  Using cached https://files.pythonhosted.org/packages/83/94/7179c3832a6d45b266ddb2aac329e101367fbdb11f425f13771d27f225bb/jmespath-0.9.4-py2.py3-none-any.whl
Requirement already satisfied: pip<19.4,>=9 in ./venv/lib/python3.7/site-packages (from chalice) (19.0.3)
Collecting enum-compat>=0.0.2 (from chalice)
  Using cached https://files.pythonhosted.org/packages/55/ae/467bc4509246283bb59746e21a1a2f5a8aecbef56b1fa6eaca78cd438c8b/enum_compat-0.0.3-py3-none-any.whl
Collecting wheel (from chalice)
  Using cached https://files.pythonhosted.org/packages/8c/23/848298cccf8e40f5bbb59009b32848a4c38f4e7f3364297ab3c3e2e2cd14/wheel-0.34.2-py2.py3-none-any.whl
Collecting attrs<20.0.0,>=17.4.0 (from chalice)
  Using cached https://files.pythonhosted.org/packages/a2/db/4313ab3be961f7a763066401fb77f7748373b6094076ae2bda2806988af6/attrs-19.3.0-py2.py3-none-any.whl
Collecting docutils<0.16,>=0.10 (from botocore<2.0.0,>=1.12.86->chalice)
  Using cached https://files.pythonhosted.org/packages/22/cd/a6aa959dca619918ccb55023b4cb151949c64d4d5d55b3f4ffd7eee0c6e8/docutils-0.15.2-py3-none-any.whl
Collecting python-dateutil<3.0.0,>=2.1 (from botocore<2.0.0,>=1.12.86->chalice)
  Using cached https://files.pythonhosted.org/packages/d4/70/d60450c3dd48ef87586924207ae8907090de0b306af2bce5d134d78615cb/python_dateutil-2.8.1-py2.py3-none-any.whl
Collecting urllib3<1.26,>=1.20; python_version != "3.4" (from botocore<2.0.0,>=1.12.86->chalice)
  Using cached https://files.pythonhosted.org/packages/e8/74/6e4f91745020f967d09332bb2b8b9b10090957334692eb88ea4afe91b77f/urllib3-1.25.8-py2.py3-none-any.whl
Installing collected packages: docutils, six, python-dateutil, urllib3, jmespath, botocore, click, enum-compat, wheel, attrs, chalice
Successfully installed attrs-19.3.0 botocore-1.15.5 chalice-1.12.0 click-7.0 docutils-0.15.2 enum-compat-0.0.3 jmespath-0.9.4 python-dateutil-2.8.1 six-1.14.0 urllib3-1.25.8 wheel-0.34.2
You are using pip version 19.0.3, however version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
(venv) /tmp/repro $ chalice new-project test1
(venv) /tmp/repro $ cd test1
(venv) /tmp/repro/test1 $ # Check that watchdog is not installed
(venv) /tmp/repro/test1 $ python
Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 16:52:21)
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import watchdog
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'watchdog'
>>> ^D
(venv) /tmp/repro/test1 $ chalice local
Serving on http://127.0.0.1:8000
Restarting local dev server.
Serving on http://127.0.0.1:8000
```

**Comment by Misza13** [comment]
@jamesls I had the same issue yesterday. The repro is quite trivial:

    git clone https://github.com/aws/chalice.git
    cd chalice
    pipenv install -r requirements-dev.txt

Make the development version available in current pipenv:

    pipenv install -e .

Then:

    pipenv run chalice

```
Traceback (most recent call last):
  File "/home/misza/.local/share/virtualenvs/chalice-gy2beJSv/bin/chalice", line 11, in <module>
    load_entry_point('chalice', 'console_scripts', 'chalice')()
  File "/home/misza/.local/share/virtualenvs/chalice-gy2beJSv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/misza/.local/share/virtualenvs/chalice-gy2beJSv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2854, in load_entry_point
    return ep.load()
  File "/home/misza/.local/share/virtualenvs/chalice-gy2beJSv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2445, in load
    return self.resolve()
  File "/home/misza/.local/share/virtualenvs/chalice-gy2beJSv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2451, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/misza/report/chalice/chalice/cli/__init__.py", line 26, in <module>
    from chalice.cli import reloader
  File "/home/misza/report/chalice/chalice/cli/reloader.py", line 34, in <module>
    from chalice.cli.filewatch.eventbased import WatchdogWorkerProcess
  File "/home/misza/report/chalice/chalice/cli/filewatch/eventbased.py", line 4, in <module>
    import watchdog.observers
ModuleNotFoundError: No module named 'watchdog'
```
