### ISSUE TITLE
I get IndexError: list index out of range , while deploying the service

### ISSUE THREAD

**Issue by swapnil1994** [aws/chalice#1419]
I have observed it many times if a requirement added in requirement.txt has supporting dependencies, I get IndexError: list index out of range, or if the number of requirements exceeds in requirement.txt file even then I get a similar error.
Any help would be appreciated.

Thanks

**Comment by kapilt** [comment]
do you have the full traceback?

**Comment by swapnil1994** [comment]
thanks for your time, here is the traceback 
Creating deployment package.
Traceback (most recent call last):
  File "c:\users\appdata\local\programs\python\python37\lib\site-packages\chalice\cli\__init__.py", line 518, in main
    return cli(obj={})
  File "c:\users\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "c:\users\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "c:\users\appdata\local\programs\python\python37\lib\site-packages\click\decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "c:\users\appdata\local\programs\python\python37\lib\site-packages\chalice\cli\__init__.py", line 205, in deploy
    deployed_values = d.deploy(config, chalice_stage_name=stage)
  File "c:\users\appdata\local\programs\python\python37\lib\site-packages\chalice\deploy\deployer.py", line 342, in deploy
    return self._deploy(config, chalice_stage_name)
  File "c:\users\appdata\local\programs\python\python37\lib\site-packages\chalice\deploy\deployer.py", line 352, in _deploy
    self._build_stage.execute(config, resources)
  File "c:\users\appdata\local\programs\python\python37\lib\site-packages\chalice\deploy\deployer.py", line 995, in execute
    step.handle(config, resource)
  File "c:\users\appdata\local\programs\python\python37\lib\site-packages\chalice\deploy\deployer.py", line 851, in handle
    handler(config, resource)
  File "c:\users\appdata\local\programs\python\python37\lib\site-packages\chalice\deploy\deployer.py", line 878, in handle_deploymentpackage
    config.project_dir, config.lambda_python_version)
  File "c:\users\appdata\local\programs\python\python37\lib\site-packages\chalice\deploy\packager.py", line 95, in create_deployment_package
    abi, requirements_filepath, site_packages_dir)
  File "c:\users\appdata\local\programs\python\python37\lib\site-packages\chalice\deploy\packager.py", line 538, in build_site_packages
    abi, tempdir, requirements_filepath)
  File "c:\users\appdata\local\programs\python\python37\lib\site-packages\chalice\deploy\packager.py", line 433, in _download_dependencies
    sdists = self._find_sdists(directory)
  File "c:\users\appdata\local\programs\python\python37\lib\site-packages\chalice\deploy\packager.py", line 349, in _find_sdists
    in self._osutils.get_directory_contents(directory)]
  File "c:\users\appdata\local\programs\python\python37\lib\site-packages\chalice\deploy\packager.py", line 348, in <listcomp>
    packages = [Package(directory, filename) for filename
  File "c:\users\appdata\local\programs\python\python37\lib\site-packages\chalice\deploy\packager.py", line 554, in __init__
    self._name, self._version = self._calculate_name_and_version()
  File "c:\users\appdata\local\programs\python\python37\lib\site-packages\chalice\deploy\packager.py", line 615, in _calculate_name_and_version
    sdist_path)
  File "c:\users\appdata\local\programs\python\python37\lib\site-packages\chalice\deploy\packager.py", line 685, in get_package_name_and_version
    pkg_info_filepath = self._generate_egg_info(package_dir)
  File "c:\users\appdata\local\programs\python\python37\lib\site-packages\chalice\deploy\packager.py", line 666, in _generate_egg_info
    egg_info_dir, info_contents[0], 'PKG-INFO')
IndexError: list index out of range

**Comment by jamesls** [comment]
What version of Chalice are you using?  That looks similar to a regression we had a while back (https://github.com/aws/chalice/issues/1398) which is fixed in the latest version of Chalice.

Let me know if you're still seeing this issue on the latest version, and if you could share the contents of your requirements.txt file that'd be helpful as well.

**Comment by swapnil1994** [comment]
hey @jamesls this is my chalice version, chalice 1.13.0, python 3.7.4, windows 10
and talking about my requirement.txt I just have a single requirement kiteconnect 
thanks

**Comment by jamesls** [comment]
Oh ok yeah so this should be fixed in version 1.14.0 (https://github.com/aws/chalice/issues/1398).  Can you upgrade to 1.14.0 and see if you're still seeing the issue?

**Comment by SooLee** [comment]
Hello I'm having the exact same issue with 1.14.0. Any suggestion?
