### ISSUE TITLE
UnrecognizedClientException depending on the AWS_DEFAULT_REGION

### ISSUE THREAD

**Issue by peterbe** [aws/chalice#1445]
This works:
```
AWS_DEFAULT_REGION=us-west-2 chalice deploy --profile relayer
```

But this doesn't:
``` 
AWS_DEFAULT_REGION=ap-east-1 chalice deploy --profile relayer
```

I get:

```
▶ AWS_DEFAULT_REGION=ap-east-1 chalice deploy --profile relayer
Creating deployment package.
Traceback (most recent call last):
  File "/Users/peterbe/.pyenv/versions/3.8.3/envs/http-request-relay/lib/python3.8/site-packages/chalice/deploy/deployer.py", line 353, in deploy
    return self._deploy(config, chalice_stage_name)
  File "/Users/peterbe/.pyenv/versions/3.8.3/envs/http-request-relay/lib/python3.8/site-packages/chalice/deploy/deployer.py", line 364, in _deploy
    plan = self._plan_stage.execute(resources)
  File "/Users/peterbe/.pyenv/versions/3.8.3/envs/http-request-relay/lib/python3.8/site-packages/chalice/deploy/planner.py", line 139, in execute
    result = handler(resource)
  File "/Users/peterbe/.pyenv/versions/3.8.3/envs/http-request-relay/lib/python3.8/site-packages/chalice/deploy/planner.py", line 195, in _plan_lambdafunction
    if not self._remote_state.resource_exists(resource):
  File "/Users/peterbe/.pyenv/versions/3.8.3/envs/http-request-relay/lib/python3.8/site-packages/chalice/deploy/planner.py", line 61, in resource_exists
    result = handler(resource)
  File "/Users/peterbe/.pyenv/versions/3.8.3/envs/http-request-relay/lib/python3.8/site-packages/chalice/deploy/planner.py", line 94, in _resource_exists_lambdafunction
    return self._client.lambda_function_exists(resource.function_name)
  File "/Users/peterbe/.pyenv/versions/3.8.3/envs/http-request-relay/lib/python3.8/site-packages/chalice/awsclient.py", line 125, in lambda_function_exists
    client.get_function(FunctionName=name)
  File "/Users/peterbe/.pyenv/versions/3.8.3/envs/http-request-relay/lib/python3.8/site-packages/botocore/client.py", line 316, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/peterbe/.pyenv/versions/3.8.3/envs/http-request-relay/lib/python3.8/site-packages/botocore/client.py", line 635, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (UnrecognizedClientException) when calling the GetFunction operation: The security token included in the request is invalid.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/peterbe/.pyenv/versions/3.8.3/envs/http-request-relay/lib/python3.8/site-packages/chalice/cli/__init__.py", line 631, in main
    return cli(obj={})
  File "/Users/peterbe/.pyenv/versions/3.8.3/envs/http-request-relay/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/peterbe/.pyenv/versions/3.8.3/envs/http-request-relay/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/peterbe/.pyenv/versions/3.8.3/envs/http-request-relay/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/peterbe/.pyenv/versions/3.8.3/envs/http-request-relay/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/peterbe/.pyenv/versions/3.8.3/envs/http-request-relay/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/peterbe/.pyenv/versions/3.8.3/envs/http-request-relay/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/peterbe/.pyenv/versions/3.8.3/envs/http-request-relay/lib/python3.8/site-packages/chalice/cli/__init__.py", line 206, in deploy
    deployed_values = d.deploy(config, chalice_stage_name=stage)
  File "/Users/peterbe/.pyenv/versions/3.8.3/envs/http-request-relay/lib/python3.8/site-packages/chalice/deploy/deployer.py", line 355, in deploy
    raise ChaliceDeploymentError(e)
chalice.deploy.deployer.ChaliceDeploymentError: ERROR - While deploying your chalice application, received the following error:

 An error occurred (UnrecognizedClientException) when calling the GetFunction
 operation: The security token included in the request is invalid.

```

There's a couple of these regions that don't work and a bunch that work. I just used `us-west-2` and `ap-east-1` in the example. 

The user credentials I use (i.e. the AWS profile) is has the `AdministratorAccess` policy in IAM.

**Comment by jamesls** [comment]
The error message that the service returns is unfortunately not super helpful, but the issue is likely because you haven't opted in to the `ap-east-1` region.  The `ap-east-1`, `af-south-1`, `eu-south-1`, and the `me-south-1` region all require you to opt-in before you can use them.  More info here: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-regions-availability-zones.html#concepts-available-regions

That error message is also what you get when you actually have invalid credentials so we can't actually tell the difference between not being opted in to a region vs. being opted in but not having valid credentials.  We could maybe add a heuristic to check your current region and see if you're opted in.  It looks like `aws ec2 describe-regions --all-regions` can give us that info.

**Comment by peterbe** [comment]
Thank you so much! I'll spend some time with that documentation. I'll figure it out. 

The question is; what do we do for Chalice? Perhaps we can put a blurb in the documentation that says something like "If you get a `UnrecognizedClientException` exception when trying to deploy, be aware the the same error can occur if the credentials is wrong *or* if you're trying to deploy into a region you haven't _opt'ed in to_".

Then, schmucks like me could Google for that error or search for it in the Chalice documentation and get a clue.

**Comment by peterbe** [comment]
Also, super helpful to myself and whoever google'd themselves to this issue. 

Open https://console.aws.amazon.com/billing/home?#/account?AWS-Regions to get a list of your enabled regions and an action to enable these regions.

**Comment by jamesls** [comment]
I like that idea.  We could have a page of "Common Issues / Troubleshooting" that we could add to the Chalice docs.

**Comment by jamesls** [comment]
Created tracking issue for troubleshooting tips here: https://github.com/aws/chalice/issues/1455
