### ISSUE TITLE
IndexError: list index out of range when datadog-lambda package is present

### ISSUE THREAD

**Issue by MehdiZonjy** [aws/chalice#1486]
`chalice deploy` fails with  `IndexError: list index out of range` when [datadog-lambda](https://pypi.org/project/datadog-lambda/) package is present.
I'm runing on chalice version `chalice 1.17.0, python 3.7.7, linux 4.19.76-linuxkit`

```
root@099d3ebf19dc:/app# chalice deploy
Creating deployment package.
Traceback (most recent call last):
  File "/opt/pyenv/versions/3.7.7/lib/python3.7/site-packages/chalice/cli/__init__.py", line 636, in main
    return cli(obj={})
  File "/opt/pyenv/versions/3.7.7/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/pyenv/versions/3.7.7/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/pyenv/versions/3.7.7/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/pyenv/versions/3.7.7/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/pyenv/versions/3.7.7/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/opt/pyenv/versions/3.7.7/lib/python3.7/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/opt/pyenv/versions/3.7.7/lib/python3.7/site-packages/chalice/cli/__init__.py", line 206, in deploy
    deployed_values = d.deploy(config, chalice_stage_name=stage)
  File "/opt/pyenv/versions/3.7.7/lib/python3.7/site-packages/chalice/deploy/deployer.py", line 354, in deploy
    return self._deploy(config, chalice_stage_name)
  File "/opt/pyenv/versions/3.7.7/lib/python3.7/site-packages/chalice/deploy/deployer.py", line 364, in _deploy
    self._build_stage.execute(config, resources)
  File "/opt/pyenv/versions/3.7.7/lib/python3.7/site-packages/chalice/deploy/deployer.py", line 546, in execute
    step.handle(config, resource)
  File "/opt/pyenv/versions/3.7.7/lib/python3.7/site-packages/chalice/deploy/deployer.py", line 394, in handle
    handler(config, resource)
  File "/opt/pyenv/versions/3.7.7/lib/python3.7/site-packages/chalice/deploy/deployer.py", line 429, in handle_deploymentpackage
    config.project_dir, config.lambda_python_version)
  File "/opt/pyenv/versions/3.7.7/lib/python3.7/site-packages/chalice/deploy/packager.py", line 95, in create_deployment_package
    abi, requirements_filepath, site_packages_dir)
  File "/opt/pyenv/versions/3.7.7/lib/python3.7/site-packages/chalice/deploy/packager.py", line 547, in build_site_packages
    abi, tempdir, requirements_filepath)
  File "/opt/pyenv/versions/3.7.7/lib/python3.7/site-packages/chalice/deploy/packager.py", line 444, in _download_dependencies
    sdists = self._find_sdists(directory)
  File "/opt/pyenv/versions/3.7.7/lib/python3.7/site-packages/chalice/deploy/packager.py", line 351, in _find_sdists
    in self._osutils.get_directory_contents(directory)]
  File "/opt/pyenv/versions/3.7.7/lib/python3.7/site-packages/chalice/deploy/packager.py", line 350, in <listcomp>
    packages = [Package(directory, filename) for filename
  File "/opt/pyenv/versions/3.7.7/lib/python3.7/site-packages/chalice/deploy/packager.py", line 563, in __init__
    self._name, self._version = self._calculate_name_and_version()
  File "/opt/pyenv/versions/3.7.7/lib/python3.7/site-packages/chalice/deploy/packager.py", line 624, in _calculate_name_and_version
    sdist_path)
  File "/opt/pyenv/versions/3.7.7/lib/python3.7/site-packages/chalice/deploy/packager.py", line 694, in get_package_name_and_version
    pkg_info_filepath = self._generate_egg_info(package_dir)
  File "/opt/pyenv/versions/3.7.7/lib/python3.7/site-packages/chalice/deploy/packager.py", line 675, in _generate_egg_info
    egg_info_dir, info_contents[0], 'PKG-INFO')
IndexError: list index out of range
```

### Steps to reproduce:
- `chalice new-project`
- add `datadog-lambda` to `requirements.txt`
- `chalice deploy`

**Comment by jamesls** [comment]
Confirmed bug, thanks for reporting.  Looking into this now.

**Comment by jamesls** [comment]
Related: https://github.com/aws/chalice/pull/1399, confirmed it's the same root cause as the linked issue, specifically this part:

>And finally, this is all just a workaround to hide the actual
issue, which is that you can't get the name/version via
setuptools/egg_info because trying to do so results in:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/var/folders/rb/4c1d0xbd18g_wxjcjlvb0whn1cjh5m/T/tmp35v4q3md/pandas-1.0.3/setup.py", line 757, in <module>
    ext_modules=maybe_cythonize(extensions, compiler_directives=directives),
  File "/var/folders/rb/4c1d0xbd18g_wxjcjlvb0whn1cjh5m/T/tmp35v4q3md/pandas-1.0.3/setup.py", line 515, in maybe_cythonize
    raise RuntimeError("Cannot cythonize without Cython installed.")
RuntimeError: Cannot cythonize without Cython installed.
```

> We fortunately don't have to deal with this issue for pandas because
we have a manylinux1 wheel available so we can skip the sdist
path entirely. However, that part of the code doesn't check
returncodes so it fails with an opaque error. We should probably
have a fallback (even if it's not 100% reliable) in this case.

In this specific case, the error is with `ddtrace`:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/var/folders/rb/4c1d0xbd18g_wxjcjlvb0whn1cjh5m/T/tmpvg1_yons/ddtrace-0.36.0/setup.py", line 11, in <module>
    from Cython.Build import cythonize  # noqa: I100
ModuleNotFoundError: No module named 'Cython'
```

This isn't an issue in the normal `pip install` case because it goes through the build dependencies which will correctly install Cython, although would still fail unless your're building on a manylinux compatible platform.

Side note, it looks like this project publishes manylinux2010 wheels.  We should look into whether we can support those in Chalice.

Working on a fix, we may just have to fall back to a best-effort file parsing approach for now.

**Comment by MehdiZonjy** [comment]
thanks for looking into this.

i managed to workaround this error by making sure `cython` is installed prior to running ` chalice deploy`

```
pip install cython
chalice deploy
```

is this related to `--no-deps` when chalice runs `pip download --no-binary=:all: --no-deps --dest ddtrace ddtrace==0.36.0` ?

**Comment by jamesls** [comment]
> is this related to --no-deps when chalice runs pip download --no-binary=:all: --no-deps ddtrace==0.36.0 ?

No, it's related to pep 517 and [build environments](https://www.python.org/dev/peps/pep-0517/#build-environment).  If you're curious on the background:

* A pep517 build can declare build dependencies.  Pip will then
  know to install these dependencies before trying to build a wheel
  file.
* When creating a build environment, it's only guaranteed to last
  for the duration of the build process.  It's not accessible once
  a pip command finishes running.
* When we try to retrieve the version of a package we run a "modified"
  form of "python setup.py egg_info".
* The problem with this is that we're not using the build environment
  that has all the build dependencies installed (it's already gone),
  so if setup.py imports a module (e.g. cython) because it expects
  it to be there because it declared it as a build dependency
  the egg_info command will fail.
* We don't check the RC or have a fallback case if we can't generate
  egg info.
* We fail with an indecipherable IndexError.

Fortunately, pep 517 specifies that an sdist built this way must have a PKG-INFO file so we can fall back to checking for this file in the root directory of the project.  I have this fix coded locally, just adding a few more tests for this case.

I've also been testing the manylinux2010/manylinux2014 wheels, and AFAICT these are compatible with Lambda so I'm also working on a separate PR that will update our packager to use those wheels.  Given that ddtrace already prebuilds these files (https://pypi.org/project/ddtrace/#files), we should be able to download the pre-existing linux wheels so we can avoid building these locally in the first place.  Should speed up your deployment, and allow non-linux users to include ddtrace in their chalice apps with a custom build step.
