### ISSUE TITLE
When setting automatic layers to true unable to import 3rd party libs specified in requirements.txt

### ISSUE THREAD

**Issue by subssn21** [aws/chalice#1493]
I tried the new automatic_layers: true option this evening, and after successfully deploying when trying to access my code via API Gateway calls I was getting the following error in the API Gateway logs:

```
(d816fe12-5308-4d17-9cc5-cabe7b16a89e) Endpoint response body before transformations:
{
"errorMessage": "Unable to import module 'app': No module named 'epsagon'",
"errorType": "Runtime.ImportModuleError"
}
```

I checked the created zip file and the library is present in the output

I did not change how I was importing it, I just use:
`import epsagon`
which works fine without automatic layers on

I have tested and everything is fine with automatic layers off on 1.18.0

**Comment by subssn21** [comment]
I should mention its Python 3.7

**Comment by SouzaPatrick** [comment]
I tried to do exactly like you, the only difference is that my python would be 3.10

╰─$ chalice invoke -n testimport
Traceback (most recent call last):
  File "/var/task/chalice/app.py", line 1756, in __call__
    return self.handler(event_obj)
  File "/var/task/chalice/app.py", line 1702, in __call__
    return self._original_func(event.to_dict(), event.context)
  File "/var/task/app.py", line 8, in testimport
    import epsagon
ModuleNotFoundError: No module named 'epsagon'
Error: Unhandled exception in Lambda function, details above.



-  My app.py
from chalice import Chalice

app = Chalice(app_name='testlayers')


@app.lambda_function()
def testimport(event, context):
    import epsagon
    return {'epsagon': epsagon.__file__}
    
    
-  My config.json
{
  "version": "2.0",
  "app_name": "layerapp",
  "automatic_layer": true,
  "stages": {
    "dev": {
      "api_gateway_stage": "api"
    }
  }
}

**Comment by SouzaPatrick** [comment]
What am I doing wrong?
