### ISSUE TITLE
error code not returned to command line when zip file is too large

### ISSUE THREAD

**Issue by mannickutd** [aws/chalice#1497]
The following output is printed to the screen but you can see at the bottom the error code is 0 returned to bash.
This should really be an error code. To replicate the error just create a requirements file with pandas and numpy included this should be larger than 50Mb that is allowed on lambda zip.

```
2020-08-24T12:58:11.1589861Z Traceback (most recent call last):
2020-08-24T12:58:11.1592763Z   File "/opt/hostedtoolcache/Python/3.7.8/x64/lib/python3.7/site-packages/chalice/awsclient.py", line 873, in _update_function_code
2020-08-24T12:58:11.1593546Z     FunctionName=function_name, ZipFile=zip_contents)
2020-08-24T12:58:11.1594394Z   File "/opt/hostedtoolcache/Python/3.7.8/x64/lib/python3.7/site-packages/botocore/client.py", line 316, in _api_call
2020-08-24T12:58:11.1595012Z     return self._make_api_call(operation_name, kwargs)
2020-08-24T12:58:11.1596050Z   File "/opt/hostedtoolcache/Python/3.7.8/x64/lib/python3.7/site-packages/botocore/client.py", line 635, in _make_api_call
2020-08-24T12:58:11.1596674Z     raise error_class(parsed_response, operation_name)
2020-08-24T12:58:11.1597441Z botocore.errorfactory.InvalidParameterValueException: An error occurred (InvalidParameterValueException) when calling the UpdateFunctionCode operation: Unzipped size must be smaller than 159509529 bytes
2020-08-24T12:58:11.1598058Z 
2020-08-24T12:58:11.1598456Z During handling of the above exception, another exception occurred:
2020-08-24T12:58:11.1598885Z 
2020-08-24T12:58:11.1599231Z Traceback (most recent call last):
2020-08-24T12:58:11.1600120Z   File "/opt/hostedtoolcache/Python/3.7.8/x64/lib/python3.7/site-packages/chalice/deploy/deployer.py", line 374, in deploy
2020-08-24T12:58:11.1600722Z     return self._deploy(config, chalice_stage_name)
2020-08-24T12:58:11.1601561Z   File "/opt/hostedtoolcache/Python/3.7.8/x64/lib/python3.7/site-packages/chalice/deploy/deployer.py", line 390, in _deploy
2020-08-24T12:58:11.1602127Z     self._executor.execute(plan)
2020-08-24T12:58:11.1602896Z   File "/opt/hostedtoolcache/Python/3.7.8/x64/lib/python3.7/site-packages/chalice/deploy/executor.py", line 43, in execute
2020-08-24T12:58:11.1603434Z     self._default_handler)(instruction)
2020-08-24T12:58:11.1604218Z   File "/opt/hostedtoolcache/Python/3.7.8/x64/lib/python3.7/site-packages/chalice/deploy/executor.py", line 55, in _do_apicall
2020-08-24T12:58:11.1605100Z     result = method(**final_kwargs)
2020-08-24T12:58:11.1605936Z   File "/opt/hostedtoolcache/Python/3.7.8/x64/lib/python3.7/site-packages/chalice/awsclient.py", line 852, in update_function
2020-08-24T12:58:11.1607306Z     zip_contents=zip_contents)
2020-08-24T12:58:11.1608068Z   File "/opt/hostedtoolcache/Python/3.7.8/x64/lib/python3.7/site-packages/chalice/awsclient.py", line 880, in _update_function_code
2020-08-24T12:58:11.1608529Z     raise self._get_lambda_code_deployment_error(e, context)
2020-08-24T12:58:11.1609665Z chalice.awsclient.DeploymentPackageTooLargeError: An error occurred (InvalidParameterValueException) when calling the UpdateFunctionCode operation: Unzipped size must be smaller than 159509529 bytes
2020-08-24T12:58:11.1610185Z 
2020-08-24T12:58:11.1610456Z During handling of the above exception, another exception occurred:
2020-08-24T12:58:11.1610700Z 
2020-08-24T12:58:11.1610914Z Traceback (most recent call last):
2020-08-24T12:58:11.1611601Z   File "/opt/hostedtoolcache/Python/3.7.8/x64/lib/python3.7/site-packages/chalice/cli/__init__.py", line 636, in main
2020-08-24T12:58:11.1612064Z     return cli(obj={})
2020-08-24T12:58:11.1612806Z   File "/opt/hostedtoolcache/Python/3.7.8/x64/lib/python3.7/site-packages/click/core.py", line 829, in __call__
2020-08-24T12:58:11.1613160Z     return self.main(*args, **kwargs)
2020-08-24T12:58:11.1613999Z   File "/opt/hostedtoolcache/Python/3.7.8/x64/lib/python3.7/site-packages/click/core.py", line 782, in main
2020-08-24T12:58:11.1614336Z     rv = self.invoke(ctx)
2020-08-24T12:58:11.1614900Z   File "/opt/hostedtoolcache/Python/3.7.8/x64/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
2020-08-24T12:58:11.1615307Z     return _process_result(sub_ctx.command.invoke(sub_ctx))
2020-08-24T12:58:11.1615925Z   File "/opt/hostedtoolcache/Python/3.7.8/x64/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
2020-08-24T12:58:11.1616299Z     return ctx.invoke(self.callback, **ctx.params)
2020-08-24T12:58:11.1616922Z   File "/opt/hostedtoolcache/Python/3.7.8/x64/lib/python3.7/site-packages/click/core.py", line 610, in invoke
2020-08-24T12:58:11.1617272Z     return callback(*args, **kwargs)
2020-08-24T12:58:11.1617878Z   File "/opt/hostedtoolcache/Python/3.7.8/x64/lib/python3.7/site-packages/click/decorators.py", line 21, in new_func
2020-08-24T12:58:11.1618273Z     return f(get_current_context(), *args, **kwargs)
2020-08-24T12:58:11.1618902Z   File "/opt/hostedtoolcache/Python/3.7.8/x64/lib/python3.7/site-packages/chalice/cli/__init__.py", line 206, in deploy
2020-08-24T12:58:11.1619337Z     deployed_values = d.deploy(config, chalice_stage_name=stage)
2020-08-24T12:58:11.1619991Z   File "/opt/hostedtoolcache/Python/3.7.8/x64/lib/python3.7/site-packages/chalice/deploy/deployer.py", line 376, in deploy
2020-08-24T12:58:11.1620361Z     raise ChaliceDeploymentError(e)
2020-08-24T12:58:11.1621015Z chalice.deploy.deployer.ChaliceDeploymentError: ERROR - While sending your chalice handler code to Lambda to update function 
2020-08-24T12:58:11.1621623Z "****", received the following error:


Updating lambda function: 
{
  "resources": [
    {
      "name": "api_handler",
      "resource_type": "lambda_function",
      "lambda_arn": "*****"
    },
    {
      "name": "rest_api",
      "resource_type": "rest_api",
      "rest_api_id": "****",
      "rest_api_url": "***"
    }
  ],
  "schema_version": "2.0",
  "backend": "api"
}
Completed 432 Bytes/432 Bytes (2.6 KiB/s) with 1 file(s) remaining
upload: .chalice/deployed/dev.json to ****/chalice/dev.json

##[debug]Exit code 0 received from tool '/bin/bash'
```

**Comment by jamesls** [comment]
I followed your set of steps and I was not able to repro this, I'm seeing an RC of 2 when this happens.

Is this running in some type of CI environment?  Perhaps they're ignoring the RC there?  Here's what I get when I try this locally in my shell:

```
$ cat requirements.txt
pandas
numpy
scipy
boto3


(chalice-37) /tmp/filesize $ chalice deploy
Creating deployment package.
Updating policy for IAM role: filesize-dev
Updating lambda function: filesize-dev
Traceback (most recent call last):
  File "chalice/chalice/awsclient.py", line 873, in _update_function_code
    FunctionName=function_name, ZipFile=zip_contents)
  File ".virtualenvs/chalice-37/lib/python3.7/site-packages/botocore/client.py", line 316, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File ".virtualenvs/chalice-37/lib/python3.7/site-packages/botocore/client.py", line 635, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (RequestEntityTooLargeException) when calling the UpdateFunctionCode operation: Request must be smaller than 69905067 bytes for the UpdateFunctionCode operation

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "chalice/chalice/deploy/deployer.py", line 374, in deploy
    return self._deploy(config, chalice_stage_name)
  File "chalice/chalice/deploy/deployer.py", line 390, in _deploy
    self._executor.execute(plan)
  File "chalice/chalice/deploy/executor.py", line 43, in execute
    self._default_handler)(instruction)
  File "chalice/chalice/deploy/executor.py", line 55, in _do_apicall
    result = method(**final_kwargs)
  File "chalice/chalice/awsclient.py", line 852, in update_function
    zip_contents=zip_contents)
  File "chalice/chalice/awsclient.py", line 880, in _update_function_code
    raise self._get_lambda_code_deployment_error(e, context)
chalice.awsclient.DeploymentPackageTooLargeError: An error occurred (RequestEntityTooLargeException) when calling the UpdateFunctionCode operation: Request must be smaller than 69905067 bytes for the UpdateFunctionCode operation

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "chalice/chalice/cli/__init__.py", line 636, in main
    return cli(obj={})
  File ".virtualenvs/chalice-37/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File ".virtualenvs/chalice-37/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File ".virtualenvs/chalice-37/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File ".virtualenvs/chalice-37/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File ".virtualenvs/chalice-37/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File ".virtualenvs/chalice-37/lib/python3.7/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "chalice/chalice/cli/__init__.py", line 206, in deploy
    deployed_values = d.deploy(config, chalice_stage_name=stage)
  File "chalice/chalice/deploy/deployer.py", line 376, in deploy
    raise ChaliceDeploymentError(e)
chalice.deploy.deployer.ChaliceDeploymentError: ERROR - While sending your chalice handler code to Lambda to update function
"filesize-dev", received the following error:

 An error occurred (RequestEntityTooLargeException) when calling the
 UpdateFunctionCode operation: Request must be smaller than 69905067 bytes for
 the UpdateFunctionCode operation

This is likely because the deployment package is 55.2 MB. Lambda only allows
deployment packages that are 50.0 MB or less in size. To avoid this error,
decrease the size of your chalice application by removing code or removing
dependencies from your chalice application.

(chalice-37) /tmp/filesize $ echo $?
2

```

**Comment by mannickutd** [comment]
Hi James,

Thanks for getting back. It is azure pipeilnes trying to run a bash script
which could be the problem that it is not propagating the error correctly.

I will continue investigating.

Thanks

Nick

**Comment by davidolmo** [comment]
Same problem in a CI environment of bitbucket pipelines. I've had this problem several times as well in the past every time i've tried to change the chalice version in the CI environment above of 1.12.0. Version 1.12.0 seems to create a normal package, any higher version creates a 70MB package zip. If I try this locally it works

**Comment by davidolmo** [comment]
As I'm currently facing this problem again, I've tried to set up in a docker the image used in bitbucket pipelines that causes the packaged zip to be very big. I've seen that the difference between the packaged zip in my local windows machine with a version above 1.12.0 and and packages zip of the docker are the folders of "grpc".

Basically, with any version above 1.12.0, my windows machine packaging does not ship "grpc" and the linux machine of bitbucket pipelines ships this package, which has a 120MB size and causes the zip to be larger than the maximum size for lambda

Any ideas why is this the case? I can't increase my chalice version

**Comment by davidolmo** [comment]
after long research it seems solved now. For anyone having a similar issue in the future, for some reason I can't understand, firebase-admin python package has some dependencies that have grpcio as dependency, and upgrading chalice interfered with this this and forced grpcio to have a bugged version. After forcing the dependencies of firebase-admin to be a recent version the issue was solved:

`firebase-admin==4.4.0
google-api-core==1.23.0
google-api-python-client==1.12.5
google-auth==1.22.1
google-cloud-core==1.4.3
google-cloud-firestore==1.9.0
google-cloud-storage==1.32.0`
