### ISSUE TITLE
add validation check of .chalice/config.json to ensure all env var values are strings

### ISSUE THREAD

**Issue by mowliv** [aws/chalice#1543]
I have been using chalice and been delighted by it since starting to use it recently. However, when merging a feature branch into master of my tree, I have now come across a problem when I run **chalice deploy**:

$ chalice deploy
Traceback (most recent call last):
  File "/Users/Michael/.pyenv/versions/ananda-fire-alerts/lib/python3.8/site-packages/chalice/cli/__init__.py", line 656, in main
    return cli(obj={})
  File "/Users/Michael/.pyenv/versions/ananda-fire-alerts/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/Michael/.pyenv/versions/ananda-fire-alerts/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/Michael/.pyenv/versions/ananda-fire-alerts/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/Michael/.pyenv/versions/ananda-fire-alerts/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/Michael/.pyenv/versions/ananda-fire-alerts/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/Michael/.pyenv/versions/ananda-fire-alerts/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/Michael/.pyenv/versions/ananda-fire-alerts/lib/python3.8/site-packages/chalice/cli/__init__.py", line 216, in deploy
    deployed_values = d.deploy(config, chalice_stage_name=stage)
  File "/Users/Michael/.pyenv/versions/ananda-fire-alerts/lib/python3.8/site-packages/chalice/deploy/deployer.py", line 376, in deploy
    return self._deploy(config, chalice_stage_name)
  File "/Users/Michael/.pyenv/versions/ananda-fire-alerts/lib/python3.8/site-packages/chalice/deploy/deployer.py", line 382, in _deploy
    self._validate_config(config)
  File "/Users/Michael/.pyenv/versions/ananda-fire-alerts/lib/python3.8/site-packages/chalice/deploy/deployer.py", line 408, in _validate_config
    validate_configuration(config)
  File "/Users/Michael/.pyenv/versions/ananda-fire-alerts/lib/python3.8/site-packages/chalice/deploy/validate.py", line 40, in validate_configuration
    routes = config.chalice_app.routes
  File "/Users/Michael/.pyenv/versions/ananda-fire-alerts/lib/python3.8/site-packages/chalice/config.py", line 141, in chalice_app
    app = v()
  File "/Users/Michael/.pyenv/versions/ananda-fire-alerts/lib/python3.8/site-packages/chalice/cli/factory.py", line 273, in load_chalice_app
    self._environ.update(environment_variables)
  File "/Users/Michael/.pyenv/versions/3.8.5/lib/python3.8/_collections_abc.py", line 832, in update
    self[key] = other[key]
  File "/Users/Michael/.pyenv/versions/3.8.5/lib/python3.8/os.py", line 680, in __setitem__
    value = self.encodevalue(value)
  File "/Users/Michael/.pyenv/versions/3.8.5/lib/python3.8/os.py", line 750, in encode
    raise TypeError("str expected, not %s" % type(value).__name__)
TypeError: str expected, not int

I created a fresh chalice project and it deploys just fine to AWS lambda. I wondered whether there was a local file that was getting picked up by one of the libraries, but I've tried setting local py files aside and that doesn't resolve it.

Please advise. Thanks!

**Comment by mowliv** [comment]
I figured out the problem, it was in .chalice/config.json. I had an environment_variables line:

        "TEST": 1

Which needed to be 

        "TEST": "1"

Would recommend a validation check be added in chalice deploy to look for this problem with config files.

**Comment by jamesls** [comment]
Thanks for the suggestion, should be a straightforward update to add this validation.

**Comment by mowliv** [comment]
Awesome 😎

**Comment by jamesls** [comment]
Fixed in #1561
