### ISSUE TITLE
`chalice deploy` includes environment_variables in Python process

### ISSUE THREAD

**Issue by k0mmsussert0d** [aws/chalice#1547]
My Python script I want to deploy as a Lambda function makes a HTTP call using requests library. For whatever reason, I'm obliged to use proxy for doing so. According to [requests docs](https://requests.readthedocs.io/en/master/user/advanced/#proxies), one easy way to achieve this is setting `HTTP_PROXY` and `HTTPS_PROXY` environment variables. So I want to have them set in my Lambda function, by specifying:
```
"stages": {
    "dev": {
      "environment_variables": {
        "HTTPS_PROXY": "http://example.com:80"
      },
  }
}
```
in `.chalice/config.json`. However, for some unknown reason (I can't find any mention about this behavior in the docs), this variable is also being set for the `chalice deploy` process. In my case, for some other whatever reason, the `HTTPS_PROXY` host is only reachable by the instances in AWS account I'm deploying to. So the whole process fails to complete, because either:

- chalice can't get pip to download all the required packages:
```
C:\redacted\redacted$ chalice deploy
Creating shared layer deployment package.
Traceback (most recent call last):
  File "c:\redacted\venv-win\lib\site-packages\chalice\cli\__init__.py", line 646, in main
    return cli(obj={})
  File "c:\redacted\venv-win\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "c:\redacted\venv-win\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "c:\redacted\venv-win\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\redacted\venv-win\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\redacted\venv-win\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\redacted\venv-win\lib\site-packages\click\decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "c:\redacted\venv-win\lib\site-packages\chalice\cli\__init__.py", line 206, in deploy
    deployed_values = d.deploy(config, chalice_stage_name=stage)
  File "c:\redacted\venv-win\lib\site-packages\chalice\deploy\deployer.py", line 374, in deploy
    return self._deploy(config, chalice_stage_name)
  File "c:\redacted\venv-win\lib\site-packages\chalice\deploy\deployer.py", line 384, in _deploy
    self._build_stage.execute(config, resources)
  File "c:\redacted\venv-win\lib\site-packages\chalice\deploy\deployer.py", line 614, in execute
    step.handle(config, resource)
  File "c:\redacted\venv-win\lib\site-packages\chalice\deploy\deployer.py", line 417, in handle
    handler(config, resource)
  File "c:\redacted\venv-win\lib\site-packages\chalice\deploy\deployer.py", line 489, in handle_lambdalayer
    zip_filename = self._layer_packager.create_deployment_package(
  File "c:\redacted\venv-win\lib\site-packages\chalice\deploy\packager.py", line 370, in create_deployment_package
    self._build_python_dependencies(python_version,
  File "c:\redacted\venv-win\lib\site-packages\chalice\deploy\packager.py", line 276, in _build_python_dependencies
    self._dependency_builder.build_site_packages(
  File "c:\redacted\venv-win\lib\site-packages\chalice\deploy\packager.py", line 713, in build_site_packages
    wheels, packages_without_wheels = self._download_dependencies(
  File "c:\redacted\venv-win\lib\site-packages\chalice\deploy\packager.py", line 566, in _download_dependencies
    deps = self._download_all_dependencies(
  File "c:\redacted\venv-win\lib\site-packages\chalice\deploy\packager.py", line 496, in _download_all_dependencies
    self._pip.download_all_dependencies(requirements_filename, directory)
  File "c:\redacted\venv-win\lib\site-packages\chalice\deploy\packager.py", line 979, in download_all_dependencies
    raise NoSuchPackageError(str(package_name))
chalice.deploy.packager.NoSuchPackageError: Could not satisfy the requirement: attrs==19.3.0
```
- or, if you make package first without setting `HTTPS_PROXY` and try to re-deploy it, botocore fails to connect:
```
C:\redacted\redacted$ chalice deploy
Creating shared layer deployment package.
  Reusing existing shared layer deployment package.
Creating app deployment package.
  Reusing existing app deployment package.
Traceback (most recent call last):
  File "c:\redacted\venv-win\lib\site-packages\urllib3\connectionpool.py", line 667, in urlopen
    self._prepare_proxy(conn)
  File "c:\redacted\venv-win\lib\site-packages\urllib3\connectionpool.py", line 932, in _prepare_proxy
    conn.connect()
  File "c:\redacted\venv-win\lib\site-packages\urllib3\connection.py", line 317, in connect
    self._tunnel()
  File "C:\Users\redacted\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 900, in _tunnel
    raise OSError("Tunnel connection failed: %d %s" % (code,
OSError: Tunnel connection failed: 403 Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\redacted\venv-win\lib\site-packages\botocore\httpsession.py", line 254, in send
    urllib_response = conn.urlopen(
  File "c:\redacted\venv-win\lib\site-packages\urllib3\connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "c:\redacted\venv-win\lib\site-packages\urllib3\util\retry.py", line 379, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "c:\redacted\venv-win\lib\site-packages\urllib3\packages\six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "c:\redacted\venv-win\lib\site-packages\urllib3\connectionpool.py", line 667, in urlopen
    self._prepare_proxy(conn)
  File "c:\redacted\venv-win\lib\site-packages\urllib3\connectionpool.py", line 932, in _prepare_proxy
    conn.connect()
  File "c:\redacted\venv-win\lib\site-packages\urllib3\connection.py", line 317, in connect
    self._tunnel()
  File "C:\Users\sesa551093\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 900, in _tunnel
    raise OSError("Tunnel connection failed: %d %s" % (code,
urllib3.exceptions.ProxyError: ('Cannot connect to proxy.', OSError('Tunnel connection failed: 403 Forbidden'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\redacted\venv-win\lib\site-packages\chalice\cli\__init__.py", line 646, in main
    return cli(obj={})
  File "c:\redacted\venv-win\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "c:\redacted\venv-win\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "c:\redacted\venv-win\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\redacted\venv-win\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\redacted\venv-win\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\redacted\venv-win\lib\site-packages\click\decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "c:\redacted\venv-win\lib\site-packages\chalice\cli\__init__.py", line 206, in deploy
    deployed_values = d.deploy(config, chalice_stage_name=stage)
  File "c:\redacted\venv-win\lib\site-packages\chalice\deploy\deployer.py", line 374, in deploy
    return self._deploy(config, chalice_stage_name)
  File "c:\redacted\venv-win\lib\site-packages\chalice\deploy\deployer.py", line 388, in _deploy
    plan = self._plan_stage.execute(resources)
  File "c:\redacted\venv-win\lib\site-packages\chalice\deploy\planner.py", line 175, in execute
    result = handler(resource)
  File "c:\redacted\venv-win\lib\site-packages\chalice\deploy\planner.py", line 371, in _plan_lambdalayer
    if self._remote_state.resource_exists(resource):
  File "c:\redacted\venv-win\lib\site-packages\chalice\deploy\planner.py", line 70, in resource_exists
    result = handler(resource, *args)
  File "c:\redacted\venv-win\lib\site-packages\chalice\deploy\planner.py", line 108, in _resource_exists_lambdalayer
    return bool(self._client.get_layer_version(
  File "c:\redacted\venv-win\lib\site-packages\chalice\awsclient.py", line 352, in get_layer_version
    return client.get_layer_version_by_arn(
  File "c:\redacted\venv-win\lib\site-packages\botocore\client.py", line 337, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "c:\redacted\venv-win\lib\site-packages\botocore\client.py", line 642, in _make_api_call
    http, parsed_response = self._make_request(
  File "c:\redacted\venv-win\lib\site-packages\botocore\client.py", line 662, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
  File "c:\redacted\venv-win\lib\site-packages\botocore\endpoint.py", line 102, in make_request
    return self._send_request(request_dict, operation_model)
  File "c:\redacted\venv-win\lib\site-packages\botocore\endpoint.py", line 136, in _send_request
    while self._needs_retry(attempts, operation_model, request_dict,
  File "c:\redacted\venv-win\lib\site-packages\botocore\endpoint.py", line 253, in _needs_retry
    responses = self._event_emitter.emit(
  File "c:\redacted\venv-win\lib\site-packages\botocore\hooks.py", line 356, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "c:\redacted\venv-win\lib\site-packages\botocore\hooks.py", line 228, in emit
    return self._emit(event_name, kwargs)
  File "c:\redacted\venv-win\lib\site-packages\botocore\hooks.py", line 211, in _emit
    response = handler(**kwargs)
  File "c:\redacted\venv-win\lib\site-packages\botocore\retryhandler.py", line 183, in __call__
    if self._checker(attempts, response, caught_exception):
  File "c:\redacted\venv-win\lib\site-packages\botocore\retryhandler.py", line 250, in __call__
    should_retry = self._should_retry(attempt_number, response,
  File "c:\redacted\venv-win\lib\site-packages\botocore\retryhandler.py", line 277, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "c:\redacted\venv-win\lib\site-packages\botocore\retryhandler.py", line 316, in __call__
    checker_response = checker(attempt_number, response,
  File "c:\redacted\venv-win\lib\site-packages\botocore\retryhandler.py", line 222, in __call__
    return self._check_caught_exception(
  File "c:\redacted\venv-win\lib\site-packages\botocore\retryhandler.py", line 359, in _check_caught_exception
    raise caught_exception
  File "c:\redacted\venv-win\lib\site-packages\botocore\endpoint.py", line 200, in _do_get_response
    http_response = self._send(request)
  File "c:\redacted\venv-win\lib\site-packages\botocore\endpoint.py", line 269, in _send
    return self.http_session.send(request)
  File "c:\redacted\venv-win\lib\site-packages\botocore\httpsession.py", line 285, in send
    raise ProxyConnectionError(proxy_url=proxy_url, error=e)
botocore.exceptions.ProxyConnectionError: Failed to connect to proxy URL: "http://example.com:80"
```

Note that `botocore.exceptions.ProxyConnectionError` mentions exactly the address provided in `config.json`. I'm not using it anywhere else in my system.

**Comment by jamesls** [comment]
This is by design.  This was added so that people can avoid hard coding resource names in their applications when they package/deploy their app.  For example, you could have an S3 bucket name in your `.chalice/config.json` and then in your app.py have:

```
@app.on_s3_event(bucket=os.environ['MY_APP_BUCKET'])
def handler(event): pass
```

If you have access to the requests `Session`, I think your best option is to set the `session.proxies` var based on some other environment variable value.  That way you can still configure it in your `.chalice/config.json` and it's only a few extra lines of code.

**Comment by k0mmsussert0d** [comment]
Thank you for the explanation. That's reasonable, though I think a little note in the docs would be helpful. I had to spend some time debugging my issue.

**Comment by jowan** [comment]
Hi there, I'm getting this error now too, but I do not understand the answer.

Are we *not* supposed to have environment variables in our config.json ? or only not have variables that relate to some part of the AWS infrastructure ?
