### ISSUE TITLE
Use S3 for chalice deploy to overcome slow upload timeouts

### ISSUE THREAD

**Issue by mowliv** [aws/chalice#1567]
I sometimes am in a rural area where upload speeds are slow enough that chalice deploy times out and I cannot upload. Before using chalice, I got around this by uploading first to S3. Is there any option for doing that with chalice? Or if not, please consider this a feature request. The other nice thing S3 upload provides is a progress bar (a non-issue with fast upload speed, I know).

**Comment by mowliv** [comment]
Here's the exception I get during deploy:

$ time chalice deploy
Creating deployment package.
Reusing existing deployment package.
Updating policy for IAM role: ananda-fire-alerts-dev
Updating lambda function: ananda-fire-alerts-dev
Traceback (most recent call last):
  File "/Users/Michael/.pyenv/versions/ananda-fire-alerts/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/Users/Michael/.pyenv/versions/ananda-fire-alerts/lib/python3.8/site-packages/urllib3/connectionpool.py", line 392, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/Users/Michael/.pyenv/versions/3.8.5/lib/python3.8/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Users/Michael/.pyenv/versions/ananda-fire-alerts/lib/python3.8/site-packages/botocore/awsrequest.py", line 91, in _send_request
    rval = super(AWSConnection, self)._send_request(
  File "/Users/Michael/.pyenv/versions/3.8.5/lib/python3.8/http/client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Users/Michael/.pyenv/versions/3.8.5/lib/python3.8/http/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Users/Michael/.pyenv/versions/ananda-fire-alerts/lib/python3.8/site-packages/botocore/awsrequest.py", line 119, in _send_output
    self.send(msg)
  File "/Users/Michael/.pyenv/versions/ananda-fire-alerts/lib/python3.8/site-packages/botocore/awsrequest.py", line 203, in send
    return super(AWSConnection, self).send(str)
  File "/Users/Michael/.pyenv/versions/3.8.5/lib/python3.8/http/client.py", line 971, in send
    self.sock.sendall(data)
  File "/Users/Michael/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1204, in sendall
    v = self.send(byte_view[count:])
  File "/Users/Michael/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1173, in send
    return self._sslobj.write(data)
socket.timeout: The write operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Michael/.pyenv/versions/ananda-fire-alerts/lib/python3.8/site-packages/botocore/httpsession.py", line 254, in send
    urllib_response = conn.urlopen(
  File "/Users/Michael/.pyenv/versions/ananda-fire-alerts/lib/python3.8/site-packages/urllib3/connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "/Users/Michael/.pyenv/versions/ananda-fire-alerts/lib/python3.8/site-packages/urllib3/util/retry.py", line 379, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/Users/Michael/.pyenv/versions/ananda-fire-alerts/lib/python3.8/site-packages/urllib3/packages/six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "/Users/Michael/.pyenv/versions/ananda-fire-alerts/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/Users/Michael/.pyenv/versions/ananda-fire-alerts/lib/python3.8/site-packages/urllib3/connectionpool.py", line 392, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/Users/Michael/.pyenv/versions/3.8.5/lib/python3.8/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Users/Michael/.pyenv/versions/ananda-fire-alerts/lib/python3.8/site-packages/botocore/awsrequest.py", line 91, in _send_request
    rval = super(AWSConnection, self)._send_request(
  File "/Users/Michael/.pyenv/versions/3.8.5/lib/python3.8/http/client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Users/Michael/.pyenv/versions/3.8.5/lib/python3.8/http/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Users/Michael/.pyenv/versions/ananda-fire-alerts/lib/python3.8/site-packages/botocore/awsrequest.py", line 119, in _send_output
    self.send(msg)
  File "/Users/Michael/.pyenv/versions/ananda-fire-alerts/lib/python3.8/site-packages/botocore/awsrequest.py", line 203, in send
    return super(AWSConnection, self).send(str)
  File "/Users/Michael/.pyenv/versions/3.8.5/lib/python3.8/http/client.py", line 971, in send
    self.sock.sendall(data)
  File "/Users/Michael/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1204, in sendall
    v = self.send(byte_view[count:])
  File "/Users/Michael/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1173, in send
    return self._sslobj.write(data)
urllib3.exceptions.ProtocolError: ('Connection aborted.', timeout('The write operation timed out'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Michael/.pyenv/versions/ananda-fire-alerts/lib/python3.8/site-packages/chalice/cli/__init__.py", line 656, in main
    return cli(obj={})
  File "/Users/Michael/.pyenv/versions/ananda-fire-alerts/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/Michael/.pyenv/versions/ananda-fire-alerts/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/Michael/.pyenv/versions/ananda-fire-alerts/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/Michael/.pyenv/versions/ananda-fire-alerts/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/Michael/.pyenv/versions/ananda-fire-alerts/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/Michael/.pyenv/versions/ananda-fire-alerts/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/Michael/.pyenv/versions/ananda-fire-alerts/lib/python3.8/site-packages/chalice/cli/__init__.py", line 216, in deploy
    deployed_values = d.deploy(config, chalice_stage_name=stage)
  File "/Users/Michael/.pyenv/versions/ananda-fire-alerts/lib/python3.8/site-packages/chalice/deploy/deployer.py", line 376, in deploy
    return self._deploy(config, chalice_stage_name)
  File "/Users/Michael/.pyenv/versions/ananda-fire-alerts/lib/python3.8/site-packages/chalice/deploy/deployer.py", line 392, in _deploy
    self._executor.execute(plan)
  File "/Users/Michael/.pyenv/versions/ananda-fire-alerts/lib/python3.8/site-packages/chalice/deploy/executor.py", line 42, in execute
    getattr(self, '_do_%s' % instruction.__class__.__name__.lower(),
  File "/Users/Michael/.pyenv/versions/ananda-fire-alerts/lib/python3.8/site-packages/chalice/deploy/executor.py", line 55, in _do_apicall
    result = method(**final_kwargs)
  File "/Users/Michael/.pyenv/versions/ananda-fire-alerts/lib/python3.8/site-packages/chalice/awsclient.py", line 869, in update_function
    return_value = self._update_function_code(function_name=function_name,
  File "/Users/Michael/.pyenv/versions/ananda-fire-alerts/lib/python3.8/site-packages/chalice/awsclient.py", line 891, in _update_function_code
    return lambda_client.update_function_code(
  File "/Users/Michael/.pyenv/versions/ananda-fire-alerts/lib/python3.8/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/Michael/.pyenv/versions/ananda-fire-alerts/lib/python3.8/site-packages/botocore/client.py", line 662, in _make_api_call
    http, parsed_response = self._make_request(
  File "/Users/Michael/.pyenv/versions/ananda-fire-alerts/lib/python3.8/site-packages/botocore/client.py", line 682, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
  File "/Users/Michael/.pyenv/versions/ananda-fire-alerts/lib/python3.8/site-packages/botocore/endpoint.py", line 102, in make_request
    return self._send_request(request_dict, operation_model)
  File "/Users/Michael/.pyenv/versions/ananda-fire-alerts/lib/python3.8/site-packages/botocore/endpoint.py", line 136, in _send_request
    while self._needs_retry(attempts, operation_model, request_dict,
  File "/Users/Michael/.pyenv/versions/ananda-fire-alerts/lib/python3.8/site-packages/botocore/endpoint.py", line 253, in _needs_retry
    responses = self._event_emitter.emit(
  File "/Users/Michael/.pyenv/versions/ananda-fire-alerts/lib/python3.8/site-packages/botocore/hooks.py", line 356, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/Users/Michael/.pyenv/versions/ananda-fire-alerts/lib/python3.8/site-packages/botocore/hooks.py", line 228, in emit
    return self._emit(event_name, kwargs)
  File "/Users/Michael/.pyenv/versions/ananda-fire-alerts/lib/python3.8/site-packages/botocore/hooks.py", line 211, in _emit
    response = handler(**kwargs)
  File "/Users/Michael/.pyenv/versions/ananda-fire-alerts/lib/python3.8/site-packages/botocore/retryhandler.py", line 183, in __call__
    if self._checker(attempts, response, caught_exception):
  File "/Users/Michael/.pyenv/versions/ananda-fire-alerts/lib/python3.8/site-packages/botocore/retryhandler.py", line 250, in __call__
    should_retry = self._should_retry(attempt_number, response,
  File "/Users/Michael/.pyenv/versions/ananda-fire-alerts/lib/python3.8/site-packages/botocore/retryhandler.py", line 277, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "/Users/Michael/.pyenv/versions/ananda-fire-alerts/lib/python3.8/site-packages/botocore/retryhandler.py", line 316, in __call__
    checker_response = checker(attempt_number, response,
  File "/Users/Michael/.pyenv/versions/ananda-fire-alerts/lib/python3.8/site-packages/botocore/retryhandler.py", line 222, in __call__
    return self._check_caught_exception(
  File "/Users/Michael/.pyenv/versions/ananda-fire-alerts/lib/python3.8/site-packages/botocore/retryhandler.py", line 359, in _check_caught_exception
    raise caught_exception
  File "/Users/Michael/.pyenv/versions/ananda-fire-alerts/lib/python3.8/site-packages/botocore/endpoint.py", line 200, in _do_get_response
    http_response = self._send(request)
  File "/Users/Michael/.pyenv/versions/ananda-fire-alerts/lib/python3.8/site-packages/botocore/endpoint.py", line 269, in _send
    return self.http_session.send(request)
  File "/Users/Michael/.pyenv/versions/ananda-fire-alerts/lib/python3.8/site-packages/botocore/httpsession.py", line 291, in send
    raise ConnectionClosedError(
botocore.exceptions.ConnectionClosedError: Connection was closed before we received a valid response from endpoint URL: "https://lambda.us-west-1.amazonaws.com/2015-03-31/functions/ananda-fire-alerts-dev/code".

**Comment by mowliv** [comment]
I don't understand how the chalice deploy code works, where the API calls are getting collected into the array and then somehow called later. But I experimented by putting a retry loop into the original exception's code path, way down in 3.8.5/lib/python3.8/http/client.py and it succeeds now on the fourth retry (from the two times I've done it so far). Here's the hack I put in:

      ```
  try:
            # MVO Edit 10/31/20
            count = 0
            while True:
                try:
                    self.sock.sendall(data)
                    break
                except socket.timeout:
                    count += 1
                    if count >= 5:
                        raise
                    else:
                        print(f"MVO: ssl send - retry {count}")

        except TypeError:
            [snip]
```

Elapsed time is 4.5 minutes, which is super long but better than never. (This is with ~1 Mbps upload speed.)

**Comment by mowliv** [comment]
Have deployed about six times now, and each time it works after 4th retry (even when I turn the threshold above of possible retries up to a higher number than 5).

**Comment by Holi0317** [comment]
If you check on `chalice deploy --help`, there is a `--connection-timeout` options:

```
  --connection-timeout INTEGER    Overrides the default botocore connection
                                  timeout.
```

The [default in botocore](https://botocore.amazonaws.com/v1/documentation/api/latest/reference/config.html#botocore-config) is 60 seconds which is not enough for me either (my zip is around 45MB). Setting this to 300 fixed my issue.

I think this issue can be closed.
