### ISSUE TITLE
egg_info_dir, info_contents[0], 'PKG-INFO') IndexError: list index out of range

### ISSUE THREAD

**Issue by timetoadd** [aws/chalice#1646]
I am getting below error while performing "chalice deploy" cmd.

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/chalice/cli/__init__.py", line 631, in main
    return cli(obj={})
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/chalice/cli/__init__.py", line 206, in deploy
    deployed_values = d.deploy(config, chalice_stage_name=stage)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/chalice/deploy/deployer.py", line 353, in deploy
    return self._deploy(config, chalice_stage_name)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/chalice/deploy/deployer.py", line 363, in _deploy
    self._build_stage.execute(config, resources)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/chalice/deploy/deployer.py", line 537, in execute
    step.handle(config, resource)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/chalice/deploy/deployer.py", line 393, in handle
    handler(config, resource)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/chalice/deploy/deployer.py", line 419, in handle_deploymentpackage
    zip_filename = self._packager.create_deployment_package(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/chalice/deploy/packager.py", line 94, in create_deployment_package
    self._dependency_builder.build_site_packages(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/chalice/deploy/packager.py", line 544, in build_site_packages
    wheels, packages_without_wheels = self._download_dependencies(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/chalice/deploy/packager.py", line 442, in _download_dependencies
Mounikas-MBP:tdameritrade mounikachalasani$ chalice deploy
Creating deployment package.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/chalice/cli/__init__.py", line 631, in main
    return cli(obj={})
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/chalice/cli/__init__.py", line 206, in deploy
    deployed_values = d.deploy(config, chalice_stage_name=stage)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/chalice/deploy/deployer.py", line 353, in deploy
    return self._deploy(config, chalice_stage_name)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/chalice/deploy/deployer.py", line 363, in _deploy
    self._build_stage.execute(config, resources)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/chalice/deploy/deployer.py", line 537, in execute
    step.handle(config, resource)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/chalice/deploy/deployer.py", line 393, in handle
    handler(config, resource)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/chalice/deploy/deployer.py", line 419, in handle_deploymentpackage
    zip_filename = self._packager.create_deployment_package(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/chalice/deploy/packager.py", line 94, in create_deployment_package
    self._dependency_builder.build_site_packages(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/chalice/deploy/packager.py", line 544, in build_site_packages
    wheels, packages_without_wheels = self._download_dependencies(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/chalice/deploy/packager.py", line 442, in _download_dependencies
    sdists = self._find_sdists(directory)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/chalice/deploy/packager.py", line 348, in _find_sdists
    packages = [Package(directory, filename) for filename
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/chalice/deploy/packager.py", line 348, in <listcomp>
    packages = [Package(directory, filename) for filename
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/chalice/deploy/packager.py", line 561, in __init__
    self._name, self._version = self._calculate_name_and_version()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/chalice/deploy/packager.py", line 621, in _calculate_name_and_version
    name, version = info_fetcher.get_package_name_and_version(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/chalice/deploy/packager.py", line 692, in get_package_name_and_version
    pkg_info_filepath = self._generate_egg_info(package_dir)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/chalice/deploy/packager.py", line 673, in _generate_egg_info
    egg_info_dir, info_contents[0], 'PKG-INFO')
IndexError: list index out of range

requirements.txt file: 

requests
pytz
google-api-python-client
google-auth-httplib2
google-auth-oauthlib
timedelta

Environment: 

chalice 1.15.1, python 3.8.3, darwin 15.6.0

I would appreciate any help in resolving this issue.

**Comment by jamesls** [comment]
Looks similar to (https://github.com/aws/chalice/issues/1486), which was fixed in later versions of chalice.  Can you try upgrading to the latest version and see if you're still having those issues?

**Comment by timetoadd** [comment]
Issue is resolved after upgrading chalice. Thanks.
