### ISSUE TITLE
Pagination is not working with Chalice, it's not accepting more than one query parameter

### ISSUE THREAD

**Issue by M-Thirumal** [aws/chalice#1702]
Pagination is not working with chalice, is there any other way to implement pagination?

```
from flask import request

@app.route('/hello/{name}')
def hello_name(name):
    page = request.args.get('page', 1, int)
    print(page)
#    # '/hello/james' -> {"hello": "james"}
    return {'hello': name}
```

Error: 

```lambda- ERROR - Caught exception for path /hello/{name}
Traceback (most recent call last):
  File "/Users/thirumal/opt/anaconda3/lib/python3.8/site-packages/chalice/app.py", line 1691, in _get_view_function_response
    response = view_function(**function_args)
  File "/Users/thirumal/git/vfc-lambda/app.py", line 39, in hello_name
    page = request.args.get('page', 1, int)
  File "/Users/thirumal/opt/anaconda3/lib/python3.8/site-packages/werkzeug/local.py", line 348, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/Users/thirumal/opt/anaconda3/lib/python3.8/site-packages/werkzeug/local.py", line 307, in _get_current_object
    return self.__local()
  File "/Users/thirumal/opt/anaconda3/lib/python3.8/site-packages/flask/globals.py", line 38, in _lookup_req_object
    raise RuntimeError(_request_ctx_err_msg)
RuntimeError: Working outside of request context.

This typically means that you attempted to use functionality that needed
an active HTTP request.  Consult the documentation on testing for
information about how to avoid this problem.```

**Comment by M-Thirumal** [comment]
I tried `app.current_request.query_params` to get the query parameters but it accepts only one query parameter

```
    params = app.current_request.query_params
    print(params.get('limit'))
    print(params.get('page'))
```

The URL

[https://localhost:8000/list?page=2&limit=10](https://localhost:8000/list?page=2&limit=10)

the above code prints

```
None
2
```

**Comment by jamesls** [comment]
I'm not seeing that issue when I try your example:


```python
$ cat app.py
from chalice import Chalice

app = Chalice(app_name='test123')


@app.route('/')
def index():
    return {
        'page': app.current_request.query_params.get('page'),
        'limit': app.current_request.query_params.get('limit'),
    }




$ chalice local &
Serving on http://127.0.0.1:8000

$ $ http 'localhost:8000/?page=1&limit=10'
HTTP/1.1 200 OK
Content-Length: 25
Content-Type: application/json
Date: Mon, 19 Apr 2021 19:26:38 GMT
Server: BaseHTTP/0.6 Python/3.8.5

{
    "limit": "10",
    "page": "1"
}

127.0.0.1 - - [19/Apr/2021 15:26:38] "GET /?page=1&limit=10 HTTP/1.1" 200 -
```

From the output you have it looks like your client is not sending the limit query param.  I'd double check the request you're sending.
