### ISSUE TITLE
chalice-cdk add subscription to a lambda encounter error

### ISSUE THREAD

**Issue by Sanyorke-Han** [aws/chalice#1751]
here is the code in stack:
--------------------
class ChaliceApp(core.Stack):

    def __init__(self, scope, id, **kwargs):
        super().__init__(scope, id, **kwargs)

        self.my_topic = aws_sns.Topic(self, "SNSTest2")

        self.chalice = Chalice(
            self, 'SNSHandler', source_dir=RUNTIME_SOURCE_DIR,
            stage_config={}
        )

        self.my_topic.add_subscription(aws_sns_subscriptions.LambdaSubscription(self.chalice))
--------------------

when execute `cdk synth` the error occurs:
--------------------
jsii.errors.JavaScriptError:
  TypeError: this.fn.addPermission is not a function
      at LambdaSubscription.bind (C:\Users\shan\AppData\Local\Temp\jsii-kernel-AVWPmh\node_modules\@aws-cdk\aws-sns-subscriptions\lib\lambda.js:36:17)
      at Topic.addSubscription (C:\Users\shan\AppData\Local\Temp\jsii-kernel-AVWPmh\node_modules\@aws-cdk\aws-sns\lib\topic-base.js:22:49)
      at C:\Users\shan\AppData\Local\Temp\tmpzozpfjca\lib\program.js:7970:134
      at Kernel._wrapSandboxCode (C:\Users\shan\AppData\Local\Temp\tmpzozpfjca\lib\program.js:8582:24)
      at C:\Users\shan\AppData\Local\Temp\tmpzozpfjca\lib\program.js:7970:107
      at Kernel._ensureSync (C:\Users\shan\AppData\Local\Temp\tmpzozpfjca\lib\program.js:8563:28)
      at Kernel.invoke (C:\Users\shan\AppData\Local\Temp\tmpzozpfjca\lib\program.js:7970:34)
      at KernelHost.processRequest (C:\Users\shan\AppData\Local\Temp\tmpzozpfjca\lib\program.js:9479:36)
      at KernelHost.run (C:\Users\shan\AppData\Local\Temp\tmpzozpfjca\lib\program.js:9442:22)
      at Immediate._onImmediate (C:\Users\shan\AppData\Local\Temp\tmpzozpfjca\lib\program.js:9443:46)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "app.py", line 6, in <module>
    ChaliceApp(app, 'frdm-monitor')
  File "C:\tmp\chaliceapp\.venv\lib\site-packages\jsii\_runtime.py", line 83, in __call__
    inst = super().__call__(*args, **kwargs)
  File "C:\tmp\chaliceapp\frdm-monitor\infrastructure\stacks\chaliceapp.py", line 27, in __init__
    self.my_topic.add_subscription(aws_sns_subscriptions.LambdaSubscription(self.chalice))
  File "C:\tmp\chaliceapp\.venv\lib\site-packages\aws_cdk\aws_sns\__init__.py", line 2671, in add_subscription
    return typing.cast(None, jsii.invoke(self, "addSubscription", [subscription]))
  File "C:\tmp\chaliceapp\.venv\lib\site-packages\jsii\_kernel\__init__.py", line 128, in wrapped
    return _recursize_dereference(kernel, fn(kernel, *args, **kwargs))
  File "C:\tmp\chaliceapp\.venv\lib\site-packages\jsii\_kernel\__init__.py", line 340, in invoke
    response = self.provider.invoke(
  File "C:\tmp\chaliceapp\.venv\lib\site-packages\jsii\_kernel\providers\process.py", line 359, in invoke
    return self._process.send(request, InvokeResponse)
  File "C:\tmp\chaliceapp\.venv\lib\site-packages\jsii\_kernel\providers\process.py", line 326, in send
    raise JSIIError(resp.error) from JavaScriptError(resp.stack)
jsii.errors.JSIIError: this.fn.addPermission is not a function
Subprocess exited with error 1
--------------------

sanyorke

**Comment by Sanyorke-Han** [comment]
the lambda function code like below:
----------------
@app.on_sns_message(topic='SNSTest2')
def sns_handler(event, context):
    print(event)
----------------

**Comment by jamesls** [comment]
Chalice should automatically handle the SNS subscription for you.  You'd just need to pass in the topic name to the handler through an environment variable, e.g.  `@app.on_sns_topic(topic=os.environ['MY_TOPIC'])`.  The CDK DDB template from `chalice new-project` shows a similar example with a DDB table.
