### ISSUE TITLE
Static analysis cannot detect nested functions

### ISSUE THREAD

**Issue by jakemwood** [aws/chalice#1841]
Chalice version 1.26.2
Python 3.9

I believe this is a regression, because I'm fairly certain this worked in previous versions of Chalice.

To reproduce, try something like this:

```python
@app.route('/')
def home():
    def response_wrapper(text):
        return {"text": text}
    return response_wrapper("hello")
```

This is not our exact code, of course, but is roughly equivalent. This will create the following stack trace:

```
Traceback (most recent call last):
  File "/home/circleci/.local/lib/python3.9/site-packages/chalice/cli/__init__.py", line 636, in main
    return cli(obj={})
  File "/home/circleci/.local/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/circleci/.local/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/circleci/.local/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/circleci/.local/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/circleci/.local/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/circleci/.local/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/circleci/.local/lib/python3.9/site-packages/chalice/cli/__init__.py", line 189, in deploy
    deployed_values = d.deploy(config, chalice_stage_name=stage)
  File "/home/circleci/.local/lib/python3.9/site-packages/chalice/deploy/deployer.py", line 376, in deploy
    return self._deploy(config, chalice_stage_name)
  File "/home/circleci/.local/lib/python3.9/site-packages/chalice/deploy/deployer.py", line 386, in _deploy
    self._build_stage.execute(config, resources)
  File "/home/circleci/.local/lib/python3.9/site-packages/chalice/deploy/deployer.py", line 652, in execute
    step.handle(config, resource)
  File "/home/circleci/.local/lib/python3.9/site-packages/chalice/deploy/deployer.py", line 419, in handle
    handler(config, resource)
  File "/home/circleci/.local/lib/python3.9/site-packages/chalice/deploy/deployer.py", line 637, in handle_autogeniampolicy
    policy = self._policy_gen.generate_policy(config)
  File "/home/circleci/.local/lib/python3.9/site-packages/chalice/policy.py", line 93, in generate_policy
    app_policy = policy_from_source_code(app_source)
  File "/home/circleci/.local/lib/python3.9/site-packages/chalice/policy.py", line 28, in policy_from_source_code
    client_calls = get_client_calls_for_app(source_code)
  File "/home/circleci/.local/lib/python3.9/site-packages/chalice/analyzer.py", line 74, in get_client_calls_for_app
    binder = t.bind_types()
  File "/home/circleci/.local/lib/python3.9/site-packages/chalice/analyzer.py", line 684, in bind_types
    self.visit(self._parsed_code.parsed_ast)
  File "/usr/local/lib/python3.9/ast.py", line 407, in visit
    return visitor(node)
  File "/usr/local/lib/python3.9/ast.py", line 415, in generic_visit
    self.visit(item)
  File "/usr/local/lib/python3.9/ast.py", line 407, in visit
    return visitor(node)
  File "/home/circleci/.local/lib/python3.9/site-packages/chalice/analyzer.py", line 694, in visit_FunctionDef
    child_infer.bind_types()
  File "/home/circleci/.local/lib/python3.9/site-packages/chalice/analyzer.py", line 352, in bind_types
    self.visit(self._current_ast_namespace)
  File "/home/circleci/.local/lib/python3.9/site-packages/chalice/analyzer.py", line 662, in visit
    return ast.NodeVisitor.visit(self, node)
  File "/usr/local/lib/python3.9/ast.py", line 407, in visit
    return visitor(node)
  File "/home/circleci/.local/lib/python3.9/site-packages/chalice/analyzer.py", line 540, in visit_FunctionDef
    self.visit(child)
  File "/home/circleci/.local/lib/python3.9/site-packages/chalice/analyzer.py", line 662, in visit
    return ast.NodeVisitor.visit(self, node)
  File "/usr/local/lib/python3.9/ast.py", line 407, in visit
    return visitor(node)
  File "/home/circleci/.local/lib/python3.9/site-packages/chalice/analyzer.py", line 563, in visit_Return
    self.generic_visit(node)
  File "/usr/local/lib/python3.9/ast.py", line 417, in generic_visit
    self.visit(value)
  File "/home/circleci/.local/lib/python3.9/site-packages/chalice/analyzer.py", line 662, in visit
    return ast.NodeVisitor.visit(self, node)
  File "/usr/local/lib/python3.9/ast.py", line 407, in visit
    return visitor(node)
  File "/home/circleci/.local/lib/python3.9/site-packages/chalice/analyzer.py", line 477, in visit_Call
    self._infer_function_call(node)
  File "/home/circleci/.local/lib/python3.9/site-packages/chalice/analyzer.py", line 498, in _infer_function_call
    sub_table = self._symbol_table.lookup_sub_namespace(
  File "/home/circleci/.local/lib/python3.9/site-packages/chalice/analyzer.py", line 280, in lookup_sub_namespace
    raise ValueError("Unknown symbol name: %s" % name)
ValueError: Unknown symbol name: response_wrapper
```

However, when I declare the function like so:

```python
def response_wrapper(text):
    return {"text": text}

@app.route('/')
def home():
    return response_wrapper("hello")
```

The project will build and deploy successfully.

**Expected behavior:** I would expect to be able to declare nested functions and Chalice be able to build/deploy successfully.

**Comment by jamesls** [comment]
Looks like this is a regression introduced in 1.18.1 when trying to fix https://github.com/aws/chalice/issues/1494.  Thanks for reporting.

**Comment by Austint30** [comment]
@jamesls Has there been any progress on this bug? I am affected by this, too.

**Comment by Shubham-Padkonde** [comment]
I reproduced this on current master (`bbe2745`). `_infer_function_call` passes the call expression's line number to `lookup_sub_namespace`, but the symbol table's line identifies the function definition. Using the registered definition's line fixes the reported `response_wrapper` crash.

Nested functions also expose a second problem: entering a child scope replaces the module symbol table with the immediate parent. A helper using a module-level `boto3` import then silently loses inferred client calls. I have a local fix that retains module globals and follows enclosing scopes for free variables and helper definitions.

Six regression cases fail on isolated unmodified master and pass with the fix; all 71 analyzer tests pass. These include the original wrapper, parameterized helper, name shadowing, a client captured through two nested scopes, a sibling helper, and an explicit `global` declaration. Full `make prcheck` is still running. I inspected #2192: it addresses cached inference across calls rather than the definition-line/lexical-scope lookup here.

Investigation, implementation and validation are assisted by OpenAI Codex. No live AWS deployment has been performed.
