### ISSUE TITLE
ResourceConflictException on UpdateFunctionConfiguration operation

### ISSUE THREAD

**Issue by malaney** [aws/chalice#1844]
I use Chalice in production and recently started receiving the following message when attempting to do a `chalice deploy`

An error occurred (ResourceConflictException) when calling the 
 UpdateFunctionConfiguration operation: The operation cannot be performed at 
 this time. An update is in progress for resource: <resource_arn>.

There are no other updates to this function occurring, and no matter how many times I retry the deployment, I get the same error with the exact same resource_arn (which coincidentally seems to be the very first of several lambdas).

Here is the full traceback:

```
Traceback (most recent call last):
  File "/home/runner/work/pdc_number_management/pdc_number_management/.venv/lib/python3.6/site-packages/chalice/deploy/deployer.py", line 374, in deploy
    return self._deploy(config, chalice_stage_name)
  File "/home/runner/work/pdc_number_management/pdc_number_management/.venv/lib/python3.6/site-packages/chalice/deploy/deployer.py", line 390, in _deploy
    self._executor.execute(plan)
  File "/home/runner/work/pdc_number_management/pdc_number_management/.venv/lib/python3.6/site-packages/chalice/deploy/executor.py", line 43, in execute
    self._default_handler)(instruction)
  File "/home/runner/work/pdc_number_management/pdc_number_management/.venv/lib/python3.6/site-packages/chalice/deploy/executor.py", line 55, in _do_apicall
    result = method(**final_kwargs)
  File "/home/runner/work/pdc_number_management/pdc_number_management/.venv/lib/python3.6/site-packages/chalice/awsclient.py", line 868, in update_function
    layers=layers
  File "/home/runner/work/pdc_number_management/pdc_number_management/.venv/lib/python3.6/site-packages/chalice/awsclient.py", line 940, in _update_function_config
    max_attempts=self.LAMBDA_CREATE_ATTEMPTS
  File "/home/runner/work/pdc_number_management/pdc_number_management/.venv/lib/python3.6/site-packages/chalice/awsclient.py", line 1804, in _call_client_method_with_retries
    response = method(**kwargs)
  File "/home/runner/work/pdc_number_management/pdc_number_management/.venv/lib/python3.6/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/runner/work/pdc_number_management/pdc_number_management/.venv/lib/python3.6/site-packages/botocore/client.py", line 676, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.ResourceConflictException: An error occurred (ResourceConflictException) when calling the UpdateFunctionConfiguration operation: The operation cannot be performed at this time. An update is in progress for resource: <resource_arn>

Is this a chalice issue or a larger AWS Lambda issue?

**Comment by fadjer** [comment]
I have the same issue since yesterday. Some people say it's beacause of this: https://aws.amazon.com/de/blogs/compute/coming-soon-expansion-of-aws-lambda-states-to-all-functions/
But how to fix this with Chalice?

**Comment by fadjer** [comment]
Moving to the last chalice version (1.26.2) seems to resolve the issue

**Comment by malaney** [comment]
Yes, @fadjer, migrating to the latest version of Chalice does seem to remedy the issue.  I was previously at 1.20.1
