### ISSUE TITLE
`AttributeError: 'App' object has no attribute '_features_used'`

### ISSUE THREAD

**Issue by brno32** [aws/chalice#1900]
I'm guessing this is due to a version mismatch. I'm using the cdk integration and I'm getting the following when trying to deploy

```
Traceback (most recent call last):
  File "app.py", line 76, in <module>
    ChaliceApp(app, f"sbma-healthpack-{STAGE}")
  File "/usr/local/lib/python3.8/site-packages/jsii/_runtime.py", line 86, in __call__
    inst = super().__call__(*args, **kwargs)
  File "app.py", line 29, in __init__
    self.chalice = Chalice(
  File "/usr/local/lib/python3.8/site-packages/jsii/_runtime.py", line 86, in __call__
    inst = super().__call__(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/chalice/cdk/construct.py", line 69, in __init__
    self._package_app()
  File "/usr/local/lib/python3.8/site-packages/chalice/cdk/construct.py", line 85, in _package_app
    api.package_app(
  File "/usr/local/lib/python3.8/site-packages/chalice/api/__init__.py", line 24, in package_app
    packager.package_app(config, output_dir, stage)
  File "/usr/local/lib/python3.8/site-packages/chalice/package.py", line [12](https://github.com/Kicksaw-Consulting/sbma-healthpack/runs/5500197172?check_suite_focus=true#step:10:12)52, in package_app
    resources = self._resource_builder.construct_resources(
  File "/usr/local/lib/python3.8/site-packages/chalice/package.py", line 1[14](https://github.com/Kicksaw-Consulting/sbma-healthpack/runs/5500197172?check_suite_focus=true#step:10:14), in construct_resources
    application = self._application_builder.build(
  File "/usr/local/lib/python3.8/site-packages/chalice/deploy/appgraph.py", line 31, in build
    for function in config.chalice_app.pure_lambda_functions:
  File "/usr/local/lib/python3.8/site-packages/chalice/config.py", line 141, in chalice_app
    app = v()
  File "/usr/local/lib/python3.8/site-packages/chalice/cli/factory.py", line 277, in load_chalice_app
    app = importlib.import_module('app')
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 2[19](https://github.com/Kicksaw-Consulting/sbma-healthpack/runs/5500197172?check_suite_focus=true#step:10:19), in _call_with_frames_removed
  File "/__w/sbma-healthpack/sbma-healthpack/infra/app.py", line 76, in <module>
    ChaliceApp(app, f"sbma-healthpack-{STAGE}")
  File "/usr/local/lib/python3.8/site-packages/jsii/_runtime.py", line 86, in __call__
    inst = super().__call__(*args, **kwargs)
  File "/__w/sbma-healthpack/sbma-healthpack/infra/app.py", line 29, in __init__
    self.chalice = Chalice(
  File "/usr/local/lib/python3.8/site-packages/jsii/_runtime.py", line 86, in __call__
    inst = super().__call__(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/chalice/cdk/construct.py", line 69, in __init__
    self._package_app()
  File "/usr/local/lib/python3.8/site-packages/chalice/cdk/construct.py", line 85, in _package_app
    api.package_app(
  File "/usr/local/lib/python3.8/site-packages/chalice/api/__init__.py", line [24](https://github.com/Kicksaw-Consulting/sbma-healthpack/runs/5500197172?check_suite_focus=true#step:10:24), in package_app
    packager.package_app(config, output_dir, stage)
  File "/usr/local/lib/python3.8/site-packages/chalice/package.py", line 1[25](https://github.com/Kicksaw-Consulting/sbma-healthpack/runs/5500197172?check_suite_focus=true#step:10:25)2, in package_app
    resources = self._resource_builder.construct_resources(
  File "/usr/local/lib/python3.8/site-packages/chalice/package.py", line 114, in construct_resources
    application = self._application_builder.build(
  File "/usr/local/lib/python3.8/site-packages/chalice/deploy/appgraph.py", line 31, in build
    for function in config.chalice_app.pure_lambda_functions:
  File "/usr/local/lib/python3.8/site-packages/chalice/config.py", line 141, in chalice_app
    app = v()
  File "/usr/local/lib/python3.8/site-packages/chalice/cli/factory.py", line [28](https://github.com/Kicksaw-Consulting/sbma-healthpack/runs/5500197172?check_suite_focus=true#step:10:28)8, in load_chalice_app
    validate.validate_feature_flags(chalice_app)
  File "/usr/local/lib/python3.8/site-packages/chalice/deploy/validate.py", line 91, in validate_feature_flags
    for feature in chalice_app._features_used:
AttributeError: 'App' object has no attribute '_features_used'
```

It's just a simple stack that uses a chalice app

```
class ChaliceApp(core.Stack):
    def __init__(self, scope, id, **kwargs):
        super().__init__(scope, id, **kwargs)
        s3_bucket = s3.Bucket(self, "bucket")
        self.chalice = Chalice(
            self,
            "chalice",
            source_dir=CHALICE_SOURCE_DIR,
            stage_config={
                "environment_variables": {
                    "S3_BUCKET_NAME": s3_bucket.bucket_name,
                }
            },
        )
```

I don't have a lockfile for this project so I'm assuming it's grabbing the newer version of something. I've made no code changes and this has worked for a while

**Comment by jamesls** [comment]
That particular attribute, `_feature_used`, was added in v1.7.0 back in early 2019.  The CDK integration for Chalice was added in v1.22.0, released last year.  So I believe you are correct, this is due to a version mismatch.  I'd just ensure you're using the latest version of Chalice (if possible) and you should no longer run into this issue.

**Comment by luisfontes19** [comment]
just to leave it here for anybody else in the same situation.

My ugly workaround is to first call chalice deploy and then cdk 😅 On the cdk side I get the IAM role created by chalice and start adding more permissions for the systems that i'm creating on CDK. To get relevant info about the components created in chalice, for example to create a route53 record for the api gateway it can be done by reading a file in .chalice/deployed/STAGENAME.json

This is far from an ideal solution, but works until this bug is fixed

**Comment by NAGA-29** [comment]
python 3.8
chalice 1.29.0
CDK  2.92.0
Still suffering from the same error...
