### ISSUE TITLE
Chalice requirements.txt file does not seems to not work with xgboost, lightgbm, and scikit-learn

### ISSUE THREAD

**Issue by ivan1016017** [aws/chalice#1902]
I am trying to deploy an API for ML services using Chalice. In this process, I save all the dependencies in a requirements.txt file like this:

```
numpy==1.22.2
pandas==1.1.0
scikit-learn==1.0.2

```

However, when I run the command `chailce deploy` , I get an error

```
Traceback (most recent call last):
  File "C:\Users\ivan\DjangoProjects\MlDeploymentProjects\chalice_ml_api_aws_lambda\venv\lib\site-packages\urllib3\connectionpool.py", line 703, 
in urlopen
    httplib_response = self._make_request(
  File "C:\Users\ivan\DjangoProjects\MlDeploymentProjects\chalice_ml_api_aws_lambda\venv\lib\site-packages\urllib3\connectionpool.py", line 398, 
in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "C:\Users\ivan\DjangoProjects\MlDeploymentProjects\chalice_ml_api_aws_lambda\venv\lib\site-packages\urllib3\connection.py", line 239, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
```

I have a vanilla chalice project. This issue also happens when I use `xgboost==1.5.2
` instead. I cannot trace the errror. I would like to know if this is use to the size of the dependency or something else.

**Comment by jamesls** [comment]
Lambda has a limit to how big the deployment package can be.  When I tried your requirements file (I had to change the package versions to newer versions to get it to build), I get this error when I deploy:


```
 An error occurred (RequestEntityTooLargeException) when calling the
 CreateFunction operation: Request must be smaller than 69905067 bytes for the
 CreateFunction operation

This is likely because the deployment package is 93.6 MB. Lambda only allows
deployment packages that are 50.0 MB or less in size. To avoid this error,
decrease the size of your chalice application by removing code or removing
dependencies from your chalice application.
```

You could try build a layer that contains scikit-learn (or there might be an existing one available).
