### ISSUE TITLE
Occasional BrokenPipeError: [Errno 32] Broken pipe 

### ISSUE THREAD

**Issue by rabryan** [aws/chalice#1917]
I occasionally get the following exception in the lambda runtime.  It seems to just happen randomly every couple weeks.  This may just be a general lambda python runtime issue.  Note that duration of the lambda is 5.7 seconds whereas my chalice configuration has lambda_timeout set to 30 seconds.

START RequestId: e6d68f3a-5857-46ab-893f-e3c3c70ea085 Version: $LATEST
--
Traceback (most recent call last):
File "/var/runtime/bootstrap", line 9, in <module>
main()
File "/var/runtime/bootstrap.py", line 360, in main
event_request.deadline_time_in_ms)
File "/var/runtime/bootstrap.py", line 138, in handle_event_request
lambda_runtime_client.post_invocation_result(invoke_id, result, result_content_type)
File "/var/runtime/lambda_runtime_client.py", line 79, in post_invocation_result
self.runtime_connection.request("POST", endpoint, result_data, headers={'Content-Type': content_type})
File "/var/lang/lib/python3.7/http/client.py", line 1281, in request
self._send_request(method, url, body, headers, encode_chunked)
File "/var/lang/lib/python3.7/http/client.py", line 1327, in _send_request
self.endheaders(body, encode_chunked=encode_chunked)
File "/var/lang/lib/python3.7/http/client.py", line 1276, in endheaders
self._send_output(message_body, encode_chunked=encode_chunked)
File "/var/lang/lib/python3.7/http/client.py", line 1075, in _send_output
self.send(chunk)
File "/var/lang/lib/python3.7/http/client.py", line 997, in send
self.sock.sendall(data)
BrokenPipeError: [Errno 32] Broken pipe
END RequestId: e6d68f3a-5857-46ab-893f-e3c3c70ea085
REPORT RequestId: e6d68f3a-5857-46ab-893f-e3c3c70ea085	Duration: 5706.56 ms	Billed Duration: 5707 ms	Memory Size: 2048 MB	Max Memory Used: 448 MB
RequestId: e6d68f3a-5857-46ab-893f-e3c3c70ea085 Error: Runtime exited with error: exit status 1Runtime.ExitError

**Comment by gohyiqian** [comment]
Hi Ryan, have you fix this issue? Because i just encounter this exact issue with my lambdas too.

**Comment by rabryan** [comment]
No still getting it.  Had it happen again today in fact.

**Comment by gaston-munoz** [comment]
Hi, is there any update about this?

**Comment by gohyiqian** [comment]
My issue is due to reading of more than 20,000 records from redshift all at once. Within the lambda, I split into multiple fetch with` cursor.fetchmany(x)` instead of `cursor.fetchall()` to fetch all at once. So far no more BrokenPipeError. Hope it helps.
