### ISSUE TITLE
on_s3_event fails with same prefixes - works with terraform

### ISSUE THREAD

**Issue by flypenguin** [aws/chalice#1999]
I have the config below. when I created the same notifications using terraform and AWS SNS notifications, it worked. I don't know what the difference is, but I know that there can be two notification subscriptions which differ only in the `suffix` part, and neither in `events` nor `prefix`.

I don't know where the error comes from, but if wanted I am able to provide a terraform configuration which reproduces the _working_ state of what I described in python below.

It seems to me that some code is performing a "step by step" configuration - the first "incoming" handler is created as lambda function, but without any triggers (after the `deploy` aborted). That might explain the error message.

**EXPECTED result:** the notifications as coded below.

**ACTUAL result:** see error message at bottom.

## Python config

```python
BUCKET = "some-bucket"
EVENTS = ["s3:ObjectCreated"]
PREFIX1 = "one/
PREFIX2 = "two/"
SUFFIX1 = ".good.suffix"
SUFFIX2 = ".great.suffix"

@app.on_s3_event(
    bucket=BUCKET, events=EVENTS, prefix=PREFIX1
)
def s3_incoming(event):
    handle_incoming_event(event)


@app.on_s3_event(
    bucket=BUCKET, events=EVENTS, prefix=PREFIX2, suffix=SUFFIX1
)
def s3_processing(event):
    handle_processing_event(event)

@app.on_s3_event(
    bucket=BUCKET, events=EVENTS, prefix=PREFIX2, suffix=SUFFIX2
)
def s3_finalizeing(event):
    handle_finalizing_event(event)
```

## Error message

```
/python/path/_distutils_hack/__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
Creating deployment package.
Updating lambda function: chalice-test-prod-s3_incoming
Configuring S3 events in bucket mybucket-chalice-test-prod to function chalice-test-prod-s3_incoming
Traceback (most recent call last):
  File "/python/path/chalice/deploy/deployer.py", line 376, in deploy
    return self._deploy(config, chalice_stage_name)
  File "/python/path/chalice/deploy/deployer.py", line 392, in _deploy
    self._executor.execute(plan)
  File "/python/path/chalice/deploy/executor.py", line 42, in execute
    getattr(self, '_do_%s' % instruction.__class__.__name__.lower(),
  File "/python/path/chalice/deploy/executor.py", line 55, in _do_apicall
    result = method(**final_kwargs)
  File "/python/path/chalice/awsclient.py", line 1498, in connect_s3_bucket_to_lambda
    s3.put_bucket_notification_configuration(
  File "/python/path/botocore/client.py", line 507, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/python/path/botocore/client.py", line 943, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InvalidArgument) when calling the PutBucketNotificationConfiguration operation: Configuration is ambiguously defined. Cannot have overlapping suffixes in two rules if the prefixes are overlapping for the same event type.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/python/path/chalice/cli/__init__.py", line 636, in main
    return cli(obj={})
  File "/python/path/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/python/path/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/python/path/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/python/path/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/python/path/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/python/path/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/python/path/chalice/cli/__init__.py", line 189, in deploy
    deployed_values = d.deploy(config, chalice_stage_name=stage)
  File "/python/path/chalice/deploy/deployer.py", line 378, in deploy
    raise ChaliceDeploymentError(e)
chalice.deploy.deployer.ChaliceDeploymentError: ERROR - While deploying your chalice application, received the following error:

 An error occurred (InvalidArgument) when calling the
 PutBucketNotificationConfiguration operation: Configuration is ambiguously
 defined. Cannot have overlapping suffixes in two rules if the prefixes are
 overlapping for the same event type.
```

**Comment by flypenguin** [comment]
my bad, some other notifications were still present on the same bucket. closing.
