### ISSUE TITLE
Generating cloudformation template fails with CodeBuild does not yet support python version 'python3.10'.

### ISSUE THREAD

**Issue by marcinbarczynski** [aws/chalice#2054]
`chalice deploy` works fine but when I try to generate a cloudformation template, I get:
```
$ chalice generate-pipeline file
Traceback (most recent call last):
  File "/home/q/.virtualenvs/chalice/lib/python3.10/site-packages/chalice/pipeline.py", line 223, in _get_codebuild_image
    image_suffix = self._CODEBUILD_IMAGE[params.lambda_python_version]
KeyError: 'python3.10'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/q/.virtualenvs/chalice/lib/python3.10/site-packages/chalice/cli/__init__.py", line 637, in main
    return cli(obj={})
  File "/home/q/.virtualenvs/chalice/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/q/.virtualenvs/chalice/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/q/.virtualenvs/chalice/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/q/.virtualenvs/chalice/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/q/.virtualenvs/chalice/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/q/.virtualenvs/chalice/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/q/.virtualenvs/chalice/lib/python3.10/site-packages/chalice/cli/__init__.py", line 620, in generate_pipeline
    output = p.create_template(params)
  File "/home/q/.virtualenvs/chalice/lib/python3.10/site-packages/chalice/pipeline.py", line 205, in create_template
    params['CodeBuildImage']['Default'] = self._get_codebuild_image(
  File "/home/q/.virtualenvs/chalice/lib/python3.10/site-packages/chalice/pipeline.py", line 226, in _get_codebuild_image
    raise InvalidCodeBuildPythonVersion(str(e))
chalice.pipeline.InvalidCodeBuildPythonVersion: CodeBuild does not yet support python version 'python3.10'.
```

**Comment by xxuun** [comment]
Is this project still being maintained?
