### ISSUE TITLE
Can't parse multipart/form-data request that contains binary file

### ISSUE THREAD

**Issue by JoeStech** [aws/chalice#418]
I'd like to submit a binary file and some metadata fields together as multipart/form-data, and extract each field (including the file).

I have the following simple AWS Chalice route:
```
@app.route('/submit', methods=['POST'],
           content_types=['multipart/form-data'])
def submit():
    request_info = app.current_request.to_dict()

    return request_info
```
I then use a simple form with multipart data, including a docx file upload:

```
<form enctype="multipart/form-data" method="POST" action="http://localhost:8000/submit">
    <input name='foo' type="text">
    <br>
    <input name="bar" type="file">
    <br>
    <button type='submit'>
    Submit
    </button>
</form>
```

I get the following error:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 295, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 321, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/joe/git/compellingsciencefiction/slushreader/gui/venv/local/lib/python2.7/site-packages/chalice/local.py", line 124, in __init__
    self, request, client_address, server)  # type: ignore
  File "/usr/lib/python2.7/SocketServer.py", line 649, in __init__
    self.handle()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "/home/joe/git/compellingsciencefiction/slushreader/gui/venv/local/lib/python2.7/site-packages/chalice/local.py", line 129, in _generic_handle
    self._do_invoke_view_function(lambda_event)
  File "/home/joe/git/compellingsciencefiction/slushreader/gui/venv/local/lib/python2.7/site-packages/chalice/local.py", line 141, in _do_invoke_view_function
    response = self.app_object(lambda_event, lambda_context)
  File "/home/joe/git/compellingsciencefiction/slushreader/gui/venv/local/lib/python2.7/site-packages/chalice/app.py", line 583, in __call__
    response = response.to_dict(self.api.binary_types)
  File "/home/joe/git/compellingsciencefiction/slushreader/gui/venv/local/lib/python2.7/site-packages/chalice/app.py", line 303, in to_dict
    body = json.dumps(body, default=handle_decimals)
  File "/usr/lib/python2.7/json/__init__.py", line 250, in dumps
    sort_keys=sort_keys, **kw).encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xaa in position 306: invalid start byte
```

I can't use a different library to do multipart parsing, because I can't even get the header data. When I replace `to_dict(}` with `headers` in the code above, I get:

```
Exception happened during processing of request from ('127.0.0.1', 57960)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 295, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 321, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/joe/git/compellingsciencefiction/slushreader/gui/venv/local/lib/python2.7/site-packages/chalice/local.py", line 124, in __init__
    self, request, client_address, server)  # type: ignore
  File "/usr/lib/python2.7/SocketServer.py", line 649, in __init__
    self.handle()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "/home/joe/git/compellingsciencefiction/slushreader/gui/venv/local/lib/python2.7/site-packages/chalice/local.py", line 129, in _generic_handle
    self._do_invoke_view_function(lambda_event)
  File "/home/joe/git/compellingsciencefiction/slushreader/gui/venv/local/lib/python2.7/site-packages/chalice/local.py", line 141, in _do_invoke_view_function
    response = self.app_object(lambda_event, lambda_context)
  File "/home/joe/git/compellingsciencefiction/slushreader/gui/venv/local/lib/python2.7/site-packages/chalice/app.py", line 583, in __call__
    response = response.to_dict(self.api.binary_types)
  File "/home/joe/git/compellingsciencefiction/slushreader/gui/venv/local/lib/python2.7/site-packages/chalice/app.py", line 303, in to_dict
    body = json.dumps(body, default=handle_decimals)
  File "/usr/lib/python2.7/json/__init__.py", line 250, in dumps
    sort_keys=sort_keys, **kw).encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
ValueError: Circular reference detected
```

Is there any way to use Chalice to do perform this workflow?

**Comment by stealthycoin** [comment]
Try adding the Content-Type you are expecting to have binary data to the list of binary content types (`app.api.binary_types`).

Full binary data docs: http://chalice.readthedocs.io/en/latest/topics/views.html#binary-content
