### ISSUE TITLE
json_body not being decoded in local test web server

### ISSUE THREAD

**Issue by boak** [aws/chalice#590]
When using the local test web server, JSON requests don't seem to be getting automatically decoded and stored in `app.current_request.json_body`. If I deploy the same code to run in Lambda however, it works fine and `json_body` is accessible as expected.

When I inspected the contents of `app.current_request` during local testing, it appears as though the `raw_body` is stored as a byte-string rather than a string, which causes a `TypeError` when the JSON module attempts to decode it.

Steps to reproduce / example code:
```python
from chalice import Chalice

app = Chalice(app_name='example')
app.debug = True

@app.route('/', methods=['POST'])
def index():
    return app.current_request.json_body
```

When posting a json string to this endpoint using the local web server, a TypeError exception is thrown:

```
$ chalice local
Serving on localhost:8000
example - DEBUG - Caught exception for <function index at 0x7f276ca388c8>
Traceback (most recent call last):
  File "/home/luke.mundy/pyenv/lib/python3.5/site-packages/chalice/app.py", line 645, in _get_view_function_response
    response = view_function(**function_args)
  File "/home/luke.mundy/example/app.py", line 9, in index
    return app.current_request.json_body
  File "/home/luke.mundy/pyenv/lib/python3.5/site-packages/chalice/app.py", line 293, in json_body
    self._json_body = json.loads(self.raw_body)
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
127.0.0.1 - - [02/Nov/2017 16:36:19] "POST / HTTP/1.1" 500 -
```

The above was generated by sending a request from a separate python terminal as per the below:

```pycon
>>> import requests
>>> r = requests.post('http://localhost:8000', json={'key': 'value', 'foo': 'bar', 'a': 1})
>>> r.status_code
500
>>> r.content
b'Traceback (most recent call last):\n  File "/home/luke.mundy/pyenv/lib/python3.5/site-packages/chalice/app.py", line 645, in _ge
t_view_function_response\n    response = view_function(**function_args)\n  File "/home/luke.mundy/example/app.py", line 9, in inde
x\n    return app.current_request.json_body\n  File "/home/luke.mundy/pyenv/lib/python3.5/site-packages/chalice/app.py", line 293,
 in json_body\n    self._json_body = json.loads(self.raw_body)\n  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads\n
    s.__class__.__name__))\nTypeError: the JSON object must be str, not \'bytes\'\n'
```

However if I deploy the exact same code to lambda, it works as expected.

```
$ chalice deploy
Initial creation of lambda function.
Creating role
Creating deployment package.
Initiating first time deployment...
Deploying to: api
https://w47bw49qyk.execute-api.ap-southeast-2.amazonaws.com/api/
```
Using the same request method as before:
```pycon
>>> import requests
>>> r = requests.post('https://w47bw49qyk.execute-api.ap-southeast-2.amazonaws.com/api/', json={'key': 'value', 'foo': 'bar', 'a':
 1})
>>> r.status_code
200
>>> r.content
b'{"a": 1, "foo": "bar", "key": "value"}'
```

**Comment by dstufft** [comment]
I'm not able to reproduce this using the code as written, are you using the latest version of chalice? If not try to upgrade and see if that has resolved it for you, if it hasn't you'll need to provide more information (Python version, chalice version to start) to see if we can get this to reproduce.

**Comment by boak** [comment]
Apologies, it appears this is only an issue in python 3.5. After upgrading to 3.6 the problem goes away.
