### ISSUE TITLE
PreCreatedIAMRole no longer working in 1.2.0

### ISSUE THREAD

**Issue by kadrach** [aws/chalice#793]
```
$ chalice --version
chalice 1.2.0
$ chalice new-project hello-world && cd hello-world
```
Add to `.chalice/config.json`:
```json
{
  "version": "2.0",
  "app_name": "hello-world",
  "manage_iam_role": false,
  "iam_role_arn": "arn:aws:iam::123456789012:role/some-lambda-role",
  "stages": {
    "dev": {
      "api_gateway_stage": "api"
    }
  }
}
```

```bash
$ chalice package out
Creating deployment package.
Traceback (most recent call last):
  File "/home/kadrach/.pyenv/versions/3.6.4/lib/python3.6/site-packages/chalice/cli/__init__.py", line 357, in main
    return cli(obj={})
  File "/home/kadrach/.pyenv/versions/3.6.4/lib/python3.6/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/kadrach/.pyenv/versions/3.6.4/lib/python3.6/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/kadrach/.pyenv/versions/3.6.4/lib/python3.6/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/kadrach/.pyenv/versions/3.6.4/lib/python3.6/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/kadrach/.pyenv/versions/3.6.4/lib/python3.6/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/kadrach/.pyenv/versions/3.6.4/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/kadrach/.pyenv/versions/3.6.4/lib/python3.6/site-packages/chalice/cli/__init__.py", line 286, in package
    packager.package_app(config, out, stage)
  File "/home/kadrach/.pyenv/versions/3.6.4/lib/python3.6/site-packages/chalice/package.py", line 290, in package_app
    resources)
  File "/home/kadrach/.pyenv/versions/3.6.4/lib/python3.6/site-packages/chalice/package.py", line 82, in generate_sam_template
    handler(resource, template)
  File "/home/kadrach/.pyenv/versions/3.6.4/lib/python3.6/site-packages/chalice/package.py", line 251, in _default
    raise NotImplementedError(resource)
NotImplementedError: PreCreatedIAMRole(role_arn='arn:aws:iam::123456789012:role/some-lambda-role')
```

This used to be implemented, and I can't find any mention of it in the changelog, so assume this is a bug :)

**Comment by stealthycoin** [comment]
Looks like a bug to me.

**Comment by kadrach** [comment]
This stems from the fact that `PrecreatedIAMRole` is identified by the dependency builder as a dependency, causing the packager to want to "generate" it. A quick fix is a noop generator:

```
diff --git chalice/package.py chalice/package.py                
index c42da85..99c28fa 100644                                   
--- chalice/package.py                                          
+++ chalice/package.py                                          
@@ -82,6 +82,11 @@ class SAMTemplateGenerator(object):          
             handler(resource, template)                        
         return template                                        
                                                                
+    def _generate_precreatediamrole(self, resource, template): 
+        # type: (models.ScheduledEvent, Dict[str, Any]) -> None
+        # Nothing we need to do here                           
+        pass                                                   
+                                                               
     def _generate_scheduledevent(self, resource, template):    
         # type: (models.ScheduledEvent, Dict[str, Any]) -> None
         function_cfn_name = to_cfn_resource_name(                          
```

The packager should probably not try to generate a `PrecreatedIAMRole` in the first place (I suppose it's more of a parameter? Though CF thinks of it as a dependency), but I don't have a good understanding of the planning stage at the moment.

**Comment by jamesls** [comment]
@kadrach  Yep that's exactly it, thanks for looking into it.
