### ISSUE TITLE
AttributeError: module 'pip' has no attribute 'main'

### ISSUE THREAD

**Issue by wutachih** [aws/chalice#802]
I did a pip upgrade in my virtualenv and ran into the following error from chalice package command. Is this a known issue?

File "/Users/michaelwu/Engineering/api-dev/api-env/lib/python3.6/site-packages/chalice/cli/__init__.py", line 357, in main
    return cli(obj={})
  File "/Users/michaelwu/Engineering/api-dev/api-env/lib/python3.6/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/Users/michaelwu/Engineering/api-dev/api-env/lib/python3.6/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/Users/michaelwu/Engineering/api-dev/api-env/lib/python3.6/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/michaelwu/Engineering/api-dev/api-env/lib/python3.6/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/michaelwu/Engineering/api-dev/api-env/lib/python3.6/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/Users/michaelwu/Engineering/api-dev/api-env/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/michaelwu/Engineering/api-dev/api-env/lib/python3.6/site-packages/chalice/cli/__init__.py", line 286, in package
    packager.package_app(config, out, stage)
  File "/Users/michaelwu/Engineering/api-dev/api-env/lib/python3.6/site-packages/chalice/package.py", line 290, in package_app
    config, chalice_stage_name)
  File "/Users/michaelwu/Engineering/api-dev/api-env/lib/python3.6/site-packages/chalice/package.py", line 59, in construct_resources
    self._build_stage.execute(config, resources)
  File "/Users/michaelwu/Engineering/api-dev/api-env/lib/python3.6/site-packages/chalice/deploy/deployer.py", line 679, in execute
    step.handle(config, resource)
  File "/Users/michaelwu/Engineering/api-dev/api-env/lib/python3.6/site-packages/chalice/deploy/deployer.py", line 605, in handle
    handler(config, resource)
  File "/Users/michaelwu/Engineering/api-dev/api-env/lib/python3.6/site-packages/chalice/deploy/deployer.py", line 632, in handle_deploymentpackage
    config.project_dir, config.lambda_python_version
  File "/Users/michaelwu/Engineering/api-dev/api-env/lib/python3.6/site-packages/chalice/deploy/packager.py", line 83, in create_deployment_package
    requirements_filepath, site_packages_dir)
  File "/Users/michaelwu/Engineering/api-dev/api-env/lib/python3.6/site-packages/chalice/deploy/packager.py", line 477, in build_site_packages
    tempdir, requirements_filepath)
  File "/Users/michaelwu/Engineering/api-dev/api-env/lib/python3.6/site-packages/chalice/deploy/packager.py", line 356, in _download_dependencies
    requirements_filename, directory)
  File "/Users/michaelwu/Engineering/api-dev/api-env/lib/python3.6/site-packages/chalice/deploy/packager.py", line 318, in _download_all_dependencies
    self._pip.download_all_dependencies(requirements_filename, directory)
  File "/Users/michaelwu/Engineering/api-dev/api-env/lib/python3.6/site-packages/chalice/deploy/packager.py", line 695, in download_all_dependencies
    raise PackageDownloadError(error)
chalice.deploy.packager.PackageDownloadError: Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: module 'pip' has no attribute 'main'

**Comment by wutachih** [comment]
Yes, I fixed after clear virtualenv and reinstall chalice with pip 9. Thanks
