### ISSUE TITLE
Chalice key error in deploy / prepare

### ISSUE THREAD

**Issue by thebenwaters** [aws/chalice#914]
Stack trace
```
Traceback (most recent call last):
  File "/Users/benwaters/dev/v2/venv/lib/python3.6/site-packages/chalice/cli/__init__.py", line 447, in main
    return cli(obj={})
  File "/Users/benwaters/dev/v2/venv/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/benwaters/dev/v2/venv/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/benwaters/dev/v2/venv/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/benwaters/dev/v2/venv/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/benwaters/dev/v2/venv/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/benwaters/dev/v2/venv/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/benwaters/dev/v2/venv/lib/python3.6/site-packages/chalice/cli/__init__.py", line 376, in package
    packager.package_app(config, out, stage)
  File "/Users/benwaters/dev/v2/venv/lib/python3.6/site-packages/chalice/package.py", line 365, in package_app
    config, chalice_stage_name)
  File "/Users/benwaters/dev/v2/venv/lib/python3.6/site-packages/chalice/package.py", line 60, in construct_resources
    self._build_stage.execute(config, resources)
  File "/Users/benwaters/dev/v2/venv/lib/python3.6/site-packages/chalice/deploy/deployer.py", line 823, in execute
    step.handle(config, resource)
  File "/Users/benwaters/dev/v2/venv/lib/python3.6/site-packages/chalice/deploy/deployer.py", line 721, in handle
    handler(config, resource)
  File "/Users/benwaters/dev/v2/venv/lib/python3.6/site-packages/chalice/deploy/deployer.py", line 808, in handle_autogeniampolicy
  File "/Users/benwaters/dev/v2/venv/lib/python3.6/site-packages/chalice/deploy/deployer.py", line 808, in handle_autogeniampolicy
  File "/Users/benwaters/dev/v2/venv/lib/python3.6/site-packages/chalice/deploy/deployer.py", line 808, in handle_autogeniampolicy
  File "/Users/benwaters/dev/v2/venv/lib/python3.6/site-packages/chalice/deploy/deployer.py", line 808, in handle_autogeniampolicy
  File "/Users/benwaters/dev/v2/venv/lib/python3.6/site-packages/chalice/deploy/deployer.py", line 808, in handle_autogeniampolicy
  File "/Users/benwaters/dev/v2/venv/lib/python3.6/site-packages/chalice/deploy/deployer.py", line 808, in handle_autogeniampolicy
  File "/Users/benwaters/dev/v2/venv/lib/python3.6/site-packages/chalice/deploy/deployer.py", line 808, in handle_autogeniampolicy
    policy = self._policy_gen.generate_policy(config)
  File "/Users/benwaters/dev/v2/venv/lib/python3.6/site-packages/chalice/policy.py", line 92, in generate_policy
    app_policy = policy_from_source_code(app_source)
  File "/Users/benwaters/dev/v2/venv/lib/python3.6/site-packages/chalice/policy.py", line 27, in policy_from_source_code
    client_calls = get_client_calls_for_app(source_code)
  File "/Users/benwaters/dev/v2/venv/lib/python3.6/site-packages/chalice/analyzer.py", line 76, in get_client_calls_for_app
    binder = t.bind_types()
  File "/Users/benwaters/dev/v2/venv/lib/python3.6/site-packages/chalice/analyzer.py", line 350, in bind_types
    self.visit(self._current_ast_namespace)
  File "/Users/benwaters/dev/v2/venv/lib/python3.6/site-packages/chalice/analyzer.py", line 658, in visit
    return ast.NodeVisitor.visit(self, node)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ast.py", line 253, in visit
    return visitor(node)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ast.py", line 261, in generic_visit
    self.visit(item)
  File "/Users/benwaters/dev/v2/venv/lib/python3.6/site-packages/chalice/analyzer.py", line 658, in visit
    return ast.NodeVisitor.visit(self, node)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ast.py", line 253, in visit
    return visitor(node)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ast.py", line 263, in generic_visit
    self.visit(value)
  File "/Users/benwaters/dev/v2/venv/lib/python3.6/site-packages/chalice/analyzer.py", line 658, in visit
    return ast.NodeVisitor.visit(self, node)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ast.py", line 253, in visit
    return visitor(node)
  File "/Users/benwaters/dev/v2/venv/lib/python3.6/site-packages/chalice/analyzer.py", line 475, in visit_Call
    self._infer_function_call(node)
  File "/Users/benwaters/dev/v2/venv/lib/python3.6/site-packages/chalice/analyzer.py", line 504, in _infer_function_call
    child_infer.bind_types()
  File "/Users/benwaters/dev/v2/venv/lib/python3.6/site-packages/chalice/analyzer.py", line 350, in bind_types
    self.visit(self._current_ast_namespace)
  File "/Users/benwaters/dev/v2/venv/lib/python3.6/site-packages/chalice/analyzer.py", line 658, in visit
    return ast.NodeVisitor.visit(self, node)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ast.py", line 253, in visit
    return visitor(node)
  File "/Users/benwaters/dev/v2/venv/lib/python3.6/site-packages/chalice/analyzer.py", line 537, in visit_FunctionDef
    self.visit(child)
  File "/Users/benwaters/dev/v2/venv/lib/python3.6/site-packages/chalice/analyzer.py", line 658, in visit
    return ast.NodeVisitor.visit(self, node)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ast.py", line 253, in visit
    return visitor(node)
  File "/Users/benwaters/dev/v2/venv/lib/python3.6/site-packages/chalice/analyzer.py", line 408, in visit_Assign
    self.generic_visit(node)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ast.py", line 261, in generic_visit
    self.visit(item)
  File "/Users/benwaters/dev/v2/venv/lib/python3.6/site-packages/chalice/analyzer.py", line 658, in visit
    return ast.NodeVisitor.visit(self, node)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ast.py", line 253, in visit
    return visitor(node)
  File "/Users/benwaters/dev/v2/venv/lib/python3.6/site-packages/chalice/analyzer.py", line 399, in visit_Name
    self._symbol_table.get_inferred_type(node.id)
  File "/Users/benwaters/dev/v2/venv/lib/python3.6/site-packages/chalice/analyzer.py", line 251, in get_inferred_type
    symbol = self._local_table.lookup(name)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/symtable.py", line 95, in lookup
    flags = self._table.symbols[name]
KeyError: 'raw_message'
```

```
@app.route('/request', methods=['POST'], authorizer=iam)
def request(environment):
    raw_message = app.current_request.json_body
    raw_message['foo'] = bar
    try:
        sqs.send_message(
            QueueUrl=os.getenv('QUEUE_URL'),
            MessageBody=json.dumps(raw_message)
        )
        return {
            'message': 'Your request has been received',
            'uuid': str(uuid4())
        }
    except ClientError as e:
        raise ChaliceViewError('Error')
```

**Comment by thebenwaters** [comment]
Looks to be the last defined function in my app.py (what ever the first variable is).

**Comment by thebenwaters** [comment]
dup of https://github.com/aws/chalice/issues/876
