### ISSUE TITLE
Cannot deploy with profile option

### ISSUE THREAD

**Issue by BigChief45** [aws/chalice#922]
I have a config file in `~/.aws/config` as documented in the [boto3 docs](http://boto3.readthedocs.io/en/latest/guide/configuration.html#aws-config-file):

```ini
[default]
aws_access_key_id=lklkasklklklklklhgklhgklh
aws_secret_access_key=ioioioerteioteiorteiotioeiort
region=us-west-1

[profile prod]
aws_access_key_id=asklakldklaklsdl
aws_secret_access_key=laklsdklakldkl1290390129013901
region=us-west-1
```

However when I try to deploy to the `prod` profile with the following command:

```bash
chalice deploy --stage prod --profile prod
```

I get the following error and stack trace:

```
Traceback (most recent call last):
  File "/home/ubuntu/workspace/venv/lib/python3.6/site-packages/chalice/cli/factory.py", line 117, in create_config_obj
    config_from_disk = self.load_project_config()
  File "/home/ubuntu/workspace/venv/lib/python3.6/site-packages/chalice/cli/factory.py", line 207, in load_project_config
    return json.loads(f.read())
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 10 column 7 (char 229)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/workspace/venv/lib/python3.6/site-packages/chalice/cli/__init__.py", line 398, in main
    return cli(obj={})
  File "/home/ubuntu/workspace/venv/lib/python3.6/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/ubuntu/workspace/venv/lib/python3.6/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/ubuntu/workspace/venv/lib/python3.6/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ubuntu/workspace/venv/lib/python3.6/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ubuntu/workspace/venv/lib/python3.6/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/ubuntu/workspace/venv/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/ubuntu/workspace/venv/lib/python3.6/site-packages/chalice/cli/__init__.py", line 172, in deploy
    api_gateway_stage=api_gateway_stage,
  File "/home/ubuntu/workspace/venv/lib/python3.6/site-packages/chalice/cli/factory.py", line 123, in create_config_obj
    % err)
RuntimeError: Unable to load the project config file: Expecting ',' delimiter: line 10 column 7 (char 229)
```

I am using Chalice **1.4.0**.

**Comment by BigChief45** [comment]
Oops my bad. It was just an error in my Chalice config file.
