### ISSUE TITLE
Cannot run chalice deploy with '--stage' parameter when using @app.on_s3_event

### ISSUE THREAD

**Issue by tmcfarlane** [aws/chalice#924]
This one is fairly obvious. 

Using chalice for s3 event triggers means you must have a pre-existing s3 bucket. When deploying with the stage parameter this creates you a new role(if enabled) and lambda but still the s3 bucket must pre-exist.

Because of this, the behavior actions performed on the bucket remains the same as a normal `chalice deploy`. **Chalice will put an event on the s3 bucket to point to the new lambda.**

So if I run `chalice deploy` and then `chalice deploy --stage test` I get this:
```
(env) GC02RK59EG8WPE:photo_analytics trentonmcfarlane$ chalice deploy --stage test
Creating deployment package.
Updating lambda function: photo_analytics-test-handler
Configuring S3 events in bucket photo-bucket-trent to function photo_analytics-test-handler
Traceback (most recent call last):
  File "/Users/trentonmcfarlane/personal/photo_analytics/env/lib/python3.6/site-packages/chalice/deploy/deployer.py", line 330, in deploy
    return self._deploy(config, chalice_stage_name)
  File "/Users/trentonmcfarlane/personal/photo_analytics/env/lib/python3.6/site-packages/chalice/deploy/deployer.py", line 343, in _deploy
    self._executor.execute(plan)
  File "/Users/trentonmcfarlane/personal/photo_analytics/env/lib/python3.6/site-packages/chalice/deploy/executor.py", line 31, in execute
    self._default_handler)(instruction)
  File "/Users/trentonmcfarlane/personal/photo_analytics/env/lib/python3.6/site-packages/chalice/deploy/executor.py", line 43, in _do_apicall
    result = method(**final_kwargs)
  File "/Users/trentonmcfarlane/personal/photo_analytics/env/lib/python3.6/site-packages/chalice/awsclient.py", line 767, in connect_s3_bucket_to_lambda
    NotificationConfiguration=existing_config,
  File "/Users/trentonmcfarlane/personal/photo_analytics/env/lib/python3.6/site-packages/botocore/client.py", line 314, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/trentonmcfarlane/personal/photo_analytics/env/lib/python3.6/site-packages/botocore/client.py", line 612, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InvalidArgument) when calling the PutBucketNotificationConfiguration operation: Configuration is ambiguously defined. Cannot have overlapping suffixes in two rules if the prefixes are overlapping for the same event type.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/trentonmcfarlane/personal/photo_analytics/env/lib/python3.6/site-packages/chalice/cli/__init__.py", line 447, in main
    return cli(obj={})
  File "/Users/trentonmcfarlane/personal/photo_analytics/env/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/trentonmcfarlane/personal/photo_analytics/env/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/trentonmcfarlane/personal/photo_analytics/env/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/trentonmcfarlane/personal/photo_analytics/env/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/trentonmcfarlane/personal/photo_analytics/env/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/trentonmcfarlane/personal/photo_analytics/env/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/trentonmcfarlane/personal/photo_analytics/env/lib/python3.6/site-packages/chalice/cli/__init__.py", line 183, in deploy
    deployed_values = d.deploy(config, chalice_stage_name=stage)
  File "/Users/trentonmcfarlane/personal/photo_analytics/env/lib/python3.6/site-packages/chalice/deploy/deployer.py", line 332, in deploy
    raise ChaliceDeploymentError(e)
chalice.deploy.deployer.ChaliceDeploymentError: ERROR - While deploying your chalice application, received the following error:

 An error occurred (InvalidArgument) when calling the
 PutBucketNotificationConfiguration operation: Configuration is ambiguously
 defined. Cannot have overlapping suffixes in two rules if the prefixes are
 overlapping for the same event type.
```

The major takeaway:
 PutBucketNotificationConfiguration operation: Configuration is ambiguously
 defined. Cannot have overlapping suffixes in two rules if the prefixes are
 overlapping for the same event type.

Regardless, chalice doesn't deploy s3 buckets and therefore you would be sharing a bucket across your stages, which is not good practice.

Solutions:

1. Deploy s3 buckets (big feature, not sure this is possible)
2. Manually deploy s3 buckets for each stage and define them in the config.json

The latter isn't a great option but it at least works around the problem.

**Comment by tmcfarlane** [comment]
It also may be possible to use environment variables per stage as shown on this page: http://chalice.readthedocs.io/en/latest/topics/configfile.html#stage-specific-configuration

Then we could write at the top of our app.py to import the s3 bucket name from the environment variables?

That seems like a decent work around. Will try this out.

**Comment by tmcfarlane** [comment]
Yep, just tried it out. This is exactly what you should do. Create the s3 buckets to use per environment and use environment variables per stage, as shown here: http://chalice.readthedocs.io/en/latest/topics/configfile.html#stage-specific-configuration
