### ISSUE TITLE
Deployment from TravisCI

### ISSUE THREAD

**Issue by BigChief45** [aws/chalice#931]
I currently want to create a pipeline that deploys to my production stage on successful TravisCI builds on the `master` branch. For this I added the following Travis configuration:

```yaml
deploy:
  provider: script
  script: bash scripts/deploy.sh
  on:
    branch: master
```

The `deploy.sh` script is simply the following:

```bash
chalice deploy --stage prod --profile prod
```

However, the deployment fails inside the build with the following errors:

```
Preparing deploy
Cleaning up git repository with `git stash --all`. If you need build artifacts for deployment, set `deploy.skip_cleanup: true`. See https://docs.travis-ci.com/user/deployment#Uploading-Files-and-skip_cleanup.
Saved working directory and index state WIP on (no branch): 82232ae Merge branch 'hotfix-1.0.5'
dpl.3
Deploying application
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/chalice/cli/__init__.py", line 398, in main
    return cli(obj={})
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/chalice/cli/__init__.py", line 180, in deploy
    deployed_values = d.deploy(config, chalice_stage_name=stage)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/chalice/deploy/deployer.py", line 330, in deploy
    return self._deploy(config, chalice_stage_name)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/chalice/deploy/deployer.py", line 341, in _deploy
    plan = self._plan_stage.execute(resources)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/chalice/deploy/planner.py", line 263, in execute
    result = handler(resource)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/chalice/deploy/planner.py", line 319, in _plan_lambdafunction
    if not self._remote_state.resource_exists(resource):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/chalice/deploy/planner.py", line 57, in resource_exists
    result = handler(resource)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/chalice/deploy/planner.py", line 90, in _resource_exists_lambdafunction
    return self._client.lambda_function_exists(resource.function_name)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/chalice/awsclient.py", line 95, in lambda_function_exists
    client = self._client('lambda')
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/chalice/awsclient.py", line 638, in _client
    service_name)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/botocore/session.py", line 828, in create_client
    verify = self.get_config_variable('ca_bundle')
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/botocore/session.py", line 279, in get_config_variable
    elif self._found_in_config_file(methods, var_config):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/botocore/session.py", line 306, in _found_in_config_file
    return var_config[0] in self.get_scoped_config()
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/botocore/session.py", line 383, in get_scoped_config
    raise ProfileNotFound(profile=profile_name)
botocore.exceptions.ProfileNotFound: The config profile (prod) could not be found
Creating deployment package.
__pycache__/app.cpython-36.pyc already exists, no checkout
chalicelib/__pycache__/__init__.cpython-36.pyc already exists, no checkout
chalicelib/__pycache__/constants.cpython-36.pyc already exists, no checkout
chalicelib/__pycache__/content_db.cpython-36.pyc already exists, no checkout
chalicelib/__pycache__/elasticsearch.cpython-36.pyc already exists, no checkout
chalicelib/__pycache__/elibro.cpython-36.pyc already exists, no checkout
chalicelib/__pycache__/mrc.cpython-36.pyc already exists, no checkout
chalicelib/__pycache__/pdf.cpython-36.pyc already exists, no checkout
chalicelib/__pycache__/text_to_speech.cpython-36.pyc already exists, no checkout
chalicelib/aws/__pycache__/__init__.cpython-36.pyc already exists, no checkout
chalicelib/aws/__pycache__/s3.cpython-36.pyc already exists, no checkout
chalicelib/aws/__pycache__/sns.cpython-36.pyc already exists, no checkout
chalicelib/aws/__pycache__/sqs.cpython-36.pyc already exists, no checkout
chalicelib/model/__pycache__/__init__.cpython-36.pyc already exists, no checkout
chalicelib/model/__pycache__/book.cpython-36.pyc already exists, no checkout
Could not restore untracked files from stash entry
Script failed with status 2
failed to deploy
```

I see that botocore fails to find the AWS config file where the profile info is stored:

```
botocore.exceptions.ProfileNotFound: The config profile (prod) could not be found
```

How can I create this file inside Travis, or bypass this file and use env vars directly? I have already set `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` as env vars inside the build... 😕

**Comment by david4096** [comment]
We're working on this. The deploy works but we'd like to reassume the same role by reusing an existing ARN. We'll let you know how it goes.

For this reason, it would be nice if we could configure the config.json location by configuration (or env vars)

**Comment by BigChief45** [comment]
So I set the encrypted AWS credentials using `travis encrypt` in my YAML file. Seems like that isn't the issue anymore but I am still getting these errors, seems they are related to git or something:

```
Creating deployment package.
__pycache__/app.cpython-36.pyc already exists, no checkout
chalicelib/__pycache__/__init__.cpython-36.pyc already exists, no checkout
chalicelib/__pycache__/constants.cpython-36.pyc already exists, no checkout
chalicelib/__pycache__/content_db.cpython-36.pyc already exists, no checkout
chalicelib/__pycache__/elasticsearch.cpython-36.pyc already exists, no checkout
chalicelib/__pycache__/elibro.cpython-36.pyc already exists, no checkout
chalicelib/__pycache__/mrc.cpython-36.pyc already exists, no checkout
chalicelib/__pycache__/pdf.cpython-36.pyc already exists, no checkout
chalicelib/__pycache__/text_to_speech.cpython-36.pyc already exists, no checkout
chalicelib/aws/__pycache__/__init__.cpython-36.pyc already exists, no checkout
chalicelib/aws/__pycache__/s3.cpython-36.pyc already exists, no checkout
chalicelib/aws/__pycache__/sns.cpython-36.pyc already exists, no checkout
chalicelib/aws/__pycache__/sqs.cpython-36.pyc already exists, no checkout
chalicelib/model/__pycache__/__init__.cpython-36.pyc already exists, no checkout
chalicelib/model/__pycache__/book.cpython-36.pyc already exists, no checkout
Could not restore untracked files from stash entry
```

Any ideas?

**Comment by stealthycoin** [comment]
Not sure since I haven't seen that before. Though you can try setting `PYTHONDONTWRITEBYTECODE=1` to prevent the creation of pyc files.
