### ISSUE TITLE
Error at deploy stage after adding variables

### ISSUE THREAD

**Issue by sbassi** [aws/chalice#973]
Here is the relevant code:

```
@app.route('URL HERE', methods=['POST'])
def post_mlsubscribe():
    request = app.current_request
    payload = request.json_body
    if 'confirmationtoken' in payload:
        token = payload['confirmationtoken']
    else:
        raise BadRequestError('Confirmation token not present')
    # Check if token in the DB
    dynamodb = boto3.resource('dynamodb')
    table = dynamodb.Table('mlconfirmationtokens')
    response = table.get_item(Key={'tokens': token},
                              ConsistentRead=True)
    # Create a new token
    token = str(datetime.datetime.utcnow())
```

I get:

```
$ chalice deploy
Traceback (most recent call last):
  File "/home/sbassi/projects/venvs/takocoinapi/lib/python3.6/site-packages/chalice/cli/__init__.py", line 447, in main
    return cli(obj={})
  File "/home/sbassi/projects/venvs/takocoinapi/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/sbassi/projects/venvs/takocoinapi/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/sbassi/projects/venvs/takocoinapi/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/sbassi/projects/venvs/takocoinapi/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/sbassi/projects/venvs/takocoinapi/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/sbassi/projects/venvs/takocoinapi/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/sbassi/projects/venvs/takocoinapi/lib/python3.6/site-packages/chalice/cli/__init__.py", line 183, in deploy
    deployed_values = d.deploy(config, chalice_stage_name=stage)
  File "/home/sbassi/projects/venvs/takocoinapi/lib/python3.6/site-packages/chalice/deploy/deployer.py", line 330, in deploy
    return self._deploy(config, chalice_stage_name)
  File "/home/sbassi/projects/venvs/takocoinapi/lib/python3.6/site-packages/chalice/deploy/deployer.py", line 340, in _deploy
    self._build_stage.execute(config, resources)
  File "/home/sbassi/projects/venvs/takocoinapi/lib/python3.6/site-packages/chalice/deploy/deployer.py", line 823, in execute
    step.handle(config, resource)
  File "/home/sbassi/projects/venvs/takocoinapi/lib/python3.6/site-packages/chalice/deploy/deployer.py", line 721, in handle
    handler(config, resource)
  File "/home/sbassi/projects/venvs/takocoinapi/lib/python3.6/site-packages/chalice/deploy/deployer.py", line 808, in handle_autogeniampolicy
    policy = self._policy_gen.generate_policy(config)
  File "/home/sbassi/projects/venvs/takocoinapi/lib/python3.6/site-packages/chalice/policy.py", line 92, in generate_policy
    app_policy = policy_from_source_code(app_source)
  File "/home/sbassi/projects/venvs/takocoinapi/lib/python3.6/site-packages/chalice/policy.py", line 27, in policy_from_source_code
    client_calls = get_client_calls_for_app(source_code)
  File "/home/sbassi/projects/venvs/takocoinapi/lib/python3.6/site-packages/chalice/analyzer.py", line 76, in get_client_calls_for_app
    binder = t.bind_types()
  File "/home/sbassi/projects/venvs/takocoinapi/lib/python3.6/site-packages/chalice/analyzer.py", line 350, in bind_types
    self.visit(self._current_ast_namespace)
  File "/home/sbassi/projects/venvs/takocoinapi/lib/python3.6/site-packages/chalice/analyzer.py", line 658, in visit
    return ast.NodeVisitor.visit(self, node)
  File "/home/sbassi/anaconda3/lib/python3.6/ast.py", line 253, in visit
    return visitor(node)
  File "/home/sbassi/anaconda3/lib/python3.6/ast.py", line 261, in generic_visit
    self.visit(item)
  File "/home/sbassi/projects/venvs/takocoinapi/lib/python3.6/site-packages/chalice/analyzer.py", line 658, in visit
    return ast.NodeVisitor.visit(self, node)
  File "/home/sbassi/anaconda3/lib/python3.6/ast.py", line 253, in visit
    return visitor(node)
  File "/home/sbassi/anaconda3/lib/python3.6/ast.py", line 263, in generic_visit
    self.visit(value)
  File "/home/sbassi/projects/venvs/takocoinapi/lib/python3.6/site-packages/chalice/analyzer.py", line 658, in visit
    return ast.NodeVisitor.visit(self, node)
  File "/home/sbassi/anaconda3/lib/python3.6/ast.py", line 253, in visit
    return visitor(node)
  File "/home/sbassi/projects/venvs/takocoinapi/lib/python3.6/site-packages/chalice/analyzer.py", line 475, in visit_Call
    self._infer_function_call(node)
  File "/home/sbassi/projects/venvs/takocoinapi/lib/python3.6/site-packages/chalice/analyzer.py", line 504, in _infer_function_call
    child_infer.bind_types()
  File "/home/sbassi/projects/venvs/takocoinapi/lib/python3.6/site-packages/chalice/analyzer.py", line 350, in bind_types
    self.visit(self._current_ast_namespace)
  File "/home/sbassi/projects/venvs/takocoinapi/lib/python3.6/site-packages/chalice/analyzer.py", line 658, in visit
    return ast.NodeVisitor.visit(self, node)
  File "/home/sbassi/anaconda3/lib/python3.6/ast.py", line 253, in visit
    return visitor(node)
  File "/home/sbassi/projects/venvs/takocoinapi/lib/python3.6/site-packages/chalice/analyzer.py", line 537, in visit_FunctionDef
    self.visit(child)
  File "/home/sbassi/projects/venvs/takocoinapi/lib/python3.6/site-packages/chalice/analyzer.py", line 658, in visit
    return ast.NodeVisitor.visit(self, node)
  File "/home/sbassi/anaconda3/lib/python3.6/ast.py", line 253, in visit
    return visitor(node)
  File "/home/sbassi/projects/venvs/takocoinapi/lib/python3.6/site-packages/chalice/analyzer.py", line 408, in visit_Assign
    self.generic_visit(node)
  File "/home/sbassi/anaconda3/lib/python3.6/ast.py", line 263, in generic_visit
    self.visit(value)
  File "/home/sbassi/projects/venvs/takocoinapi/lib/python3.6/site-packages/chalice/analyzer.py", line 658, in visit
    return ast.NodeVisitor.visit(self, node)
  File "/home/sbassi/anaconda3/lib/python3.6/ast.py", line 253, in visit
    return visitor(node)
  File "/home/sbassi/projects/venvs/takocoinapi/lib/python3.6/site-packages/chalice/analyzer.py", line 442, in visit_Call
    self.generic_visit(node)
  File "/home/sbassi/anaconda3/lib/python3.6/ast.py", line 261, in generic_visit
    self.visit(item)
  File "/home/sbassi/projects/venvs/takocoinapi/lib/python3.6/site-packages/chalice/analyzer.py", line 658, in visit
    return ast.NodeVisitor.visit(self, node)
  File "/home/sbassi/anaconda3/lib/python3.6/ast.py", line 253, in visit
    return visitor(node)
  File "/home/sbassi/projects/venvs/takocoinapi/lib/python3.6/site-packages/chalice/analyzer.py", line 442, in visit_Call
    self.generic_visit(node)
  File "/home/sbassi/anaconda3/lib/python3.6/ast.py", line 263, in generic_visit
    self.visit(value)
  File "/home/sbassi/projects/venvs/takocoinapi/lib/python3.6/site-packages/chalice/analyzer.py", line 658, in visit
    return ast.NodeVisitor.visit(self, node)
  File "/home/sbassi/anaconda3/lib/python3.6/ast.py", line 253, in visit
    return visitor(node)
  File "/home/sbassi/projects/venvs/takocoinapi/lib/python3.6/site-packages/chalice/analyzer.py", line 422, in visit_Attribute
    self.generic_visit(node)
  File "/home/sbassi/anaconda3/lib/python3.6/ast.py", line 263, in generic_visit
    self.visit(value)
  File "/home/sbassi/projects/venvs/takocoinapi/lib/python3.6/site-packages/chalice/analyzer.py", line 658, in visit
    return ast.NodeVisitor.visit(self, node)
  File "/home/sbassi/anaconda3/lib/python3.6/ast.py", line 253, in visit
    return visitor(node)
  File "/home/sbassi/projects/venvs/takocoinapi/lib/python3.6/site-packages/chalice/analyzer.py", line 422, in visit_Attribute
    self.generic_visit(node)
  File "/home/sbassi/anaconda3/lib/python3.6/ast.py", line 263, in generic_visit
    self.visit(value)
  File "/home/sbassi/projects/venvs/takocoinapi/lib/python3.6/site-packages/chalice/analyzer.py", line 658, in visit
    return ast.NodeVisitor.visit(self, node)
  File "/home/sbassi/anaconda3/lib/python3.6/ast.py", line 253, in visit
    return visitor(node)
  File "/home/sbassi/projects/venvs/takocoinapi/lib/python3.6/site-packages/chalice/analyzer.py", line 399, in visit_Name
    self._symbol_table.get_inferred_type(node.id)
  File "/home/sbassi/projects/venvs/takocoinapi/lib/python3.6/site-packages/chalice/analyzer.py", line 251, in get_inferred_type
    symbol = self._local_table.lookup(name)
  File "/home/sbassi/anaconda3/lib/python3.6/symtable.py", line 95, in lookup
    flags = self._table.symbols[name]
KeyError: 'datetime'
```

Note that if instead of using variable name token, I use never user name like token2, I get:

KeyError: 'token2'

It is very frustrating.

$ chalice --version
chalice 1.6.0, python 3.6.0, linux 4.10.0-33-generic

**Comment by stealthycoin** [comment]
Hmm I can't repro this can I see more context? I just copy and pasted your snippet and used the same version of chalice and python and it deploys without issue.

**Comment by sbassi** [comment]
will try again tonight. But the problem is not with this code as is, but when I add a new variable.

**Comment by kyleknap** [comment]
@sbassi It looks like our the ast walker is having problems with the datetime module? However, I copied and pasted your code from the second link and I was able to successfully deploy it. Would it be possible to include the app instantiation and imports in the code snippet for the broken deployment? I'm also wondering if the issue is related to Anaconda being used. In the meantime, one workaround for this to at least get the app deployed is run it with `--no-autogen-policy`:
```
chalice deploy --no-autogen-policy
```
This should allow you to skip the AST walking and get the application deployed. You will have to generate your own IAM policy though. You can read more about configuring that [here](https://chalice.readthedocs.io/en/latest/topics/configfile.html#iam-roles-and-policies). Hope this helps!
