### ISSUE TITLE
AttributeError: <botocore.errorfactory.LambdaExceptions object at 0x11313c320> object has no attribute 'ResourceInUseException'.

### ISSUE THREAD

**Issue by AndyQ** [aws/chalice#983]
Just started getting the following error when deploying one of my apps.
Any idea what may cause it?

Versions: chalice 1.6.1, python 3.6.5, darwin 18.2.0

```
Updating policy for IAM role: myapp-dev
Updating lambda function: myapp-dev
Traceback (most recent call last):
  File "/Users/andy/.virtualenvs/myapp/lib/python3.6/site-packages/chalice/cli/__init__.py", line 447, in main
    return cli(obj={})
  File "/Users/andy/.virtualenvs/myapp/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/andy/.virtualenvs/myapp/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/andy/.virtualenvs/myapp/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/andy/.virtualenvs/myapp/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/andy/.virtualenvs/myapp/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/andy/.virtualenvs/myapp/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/andy/.virtualenvs/myapp/lib/python3.6/site-packages/chalice/cli/__init__.py", line 183, in deploy
    deployed_values = d.deploy(config, chalice_stage_name=stage)
  File "/Users/andy/.virtualenvs/myapp/lib/python3.6/site-packages/chalice/deploy/deployer.py", line 330, in deploy
    return self._deploy(config, chalice_stage_name)
  File "/Users/andy/.virtualenvs/myapp/lib/python3.6/site-packages/chalice/deploy/deployer.py", line 343, in _deploy
    self._executor.execute(plan)
  File "/Users/andy/.virtualenvs/myapp/lib/python3.6/site-packages/chalice/deploy/executor.py", line 31, in execute
    self._default_handler)(instruction)
  File "/Users/andy/.virtualenvs/myapp/lib/python3.6/site-packages/chalice/deploy/executor.py", line 43, in _do_apicall
    result = method(**final_kwargs)
  File "/Users/andy/.virtualenvs/myapp/lib/python3.6/site-packages/chalice/awsclient.py", line 272, in update_function
    function_name=function_name
  File "/Users/andy/.virtualenvs/myapp/lib/python3.6/site-packages/chalice/awsclient.py", line 338, in _update_function_config
    max_attempts=self.LAMBDA_CREATE_ATTEMPTS
  File "/Users/andy/.virtualenvs/myapp/lib/python3.6/site-packages/chalice/awsclient.py", line 983, in _call_client_method_with_retries
    client.exceptions.ResourceInUseException,
  File "/Users/andy/.virtualenvs/myapp/lib/python3.6/site-packages/botocore/errorfactory.py", line 53, in __getattr__
    self, name, ', '.join(exception_cls_names)))
AttributeError: <botocore.errorfactory.LambdaExceptions object at 0x11313c320> object has no attribute 'ResourceInUseException'. Valid exceptions are: CodeStorageExceededException, EC2AccessDeniedException, EC2ThrottledException, EC2UnexpectedException, ENILimitReachedException, InvalidParameterValueException, InvalidRequestContentException, InvalidRuntimeException, InvalidSecurityGroupIDException, InvalidSubnetIDException, InvalidZipFileException, KMSAccessDeniedException, KMSDisabledException, KMSInvalidStateException, KMSNotFoundException, PolicyLengthExceededException, RequestTooLargeException, ResourceConflictException, ResourceNotFoundException, ServiceException, SubnetIPAddressLimitReachedException, TooManyRequestsException, UnsupportedMediaTypeException```

**Comment by thomasdeml** [comment]
Hi, 
I saw the same issue. Upgrading boto3 (pip install --upgrade boto3) fixed the problem. 

Thomas

**Comment by kyleknap** [comment]
@AndyQ What version of `botocore` do you have in your virtualenv? If you are running a version of botocore not in this [version range](https://github.com/aws/chalice/blob/master/setup.py#L11), specifically not higher than or equal to the `1.10.48` version, then it is possible to run into these type of runtime errors. So if you upgrade `botocore` to the latest version, you should no longer see these issues.

**Comment by AndyQ** [comment]
That was exactly it!  Thanks.
